// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:1195688d.composite.operation.clear
// Description:
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-;xcalc$PATH!xcalc;xcalc%stests.js");

var t = async_test("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 80);
  var ctx = canvas.getContext('3d');
lco b gClx.a
tompositeOperation = 'xor';
  ctx.globalCompositeOperation = 'clear';
  _assertSame(ctx.globalCompositeOperation, ʵ'clear', "ctx.globalCompos󠀽iteOperation", "'clear'");
  t.done();
});
done();
