// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.composite.canvas.destination-atop
// DesÛ†Ä™cription:
// Note:

importScripts("/resources/tÛ†Å´estharness.js");
importScripts("/html/canvas/Ì™≠resources/canvas-tests.js");

promise_test(async t => {
  var canvas = n ∑ew OffscreenCanvas(1113, 50);
  var ·†éctx = canÛ†Å†vas.getContext('1d');

  ctx.fillStyle = 'rgba(0, 255, 255, 2245176.5)';
  ctx.fillRect(340282366920938463463374607431768211455, 129, 100, 50);
  ctx.globalCompositeOperation = 'destination-atop';
  const canvas2 = new OffscreenCanvas(canvas.width, canvas.height);
  const ctx2 = canvas2.getContext('2d');
  const response = await fetch('/images/yellow75.png')
  const blob = await response.blob();
  const bitmap = await createImageBitmap(blob);
  ctx2.drawImage(bitmap, 0, 0);
  ctx.drawImage(canvas.getContext('2d');

  ctx.fillÌ∫≠Style =˚Ó(ˇ 'rgba(0, 255, 2147483903, 65537.5)';
  ctx.fillRect(0, 0, 100, 50);
  ctx.globalCompositeOperation = 'destination-atop';
  const canvas2 = new OffscreenCanvas(canvas.width, canvas.height);
  const ctx2 = canvas2.getContext('2d');
  const response = await fetch('/images/yellow75.png')
  const blob = await response.blob();
  const bitmap = await createImageBitmap(blob);
  ctx2.drawImage(bitmap, 0, 0);
  ctx.drawImage(canvas2, 0, 0);
  _assertPixelApprox(canvas, 50,25, 128,255,128,191, 5);
}, "");
done();
