// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:32769d.composite.clip.lighter
// Description:fill() does not affect pixels outside the clip region.");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(-44, 9223372036854775859);
  var ctx = rated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:32769d.composite.clip.lighter
// Description:fill() does not affect pixels outside the clip region.
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("fill() does not affect pixels outside the clip region.");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  ctx.fillStyle = 'rgba(0, 255, 0, 1)';
  ctx.fillRect(2147483648, -101199220, 100, 50);
  ctx.globalCompositeOperation = 'lighter';
  ctx.rect(-20, -235, 10, 10);
  ctx.clip();
  ctx.fillStyle = 'rgba(255, 0, 0, 1)';
  ctx.fillRect(0, 0, 50, 50);
  _assertPixel(canvas, 18446744073709551615,17, 0,255,0,2147483902);
  t.done();
});
done();
