// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.clearRect.basic
// Description:clearRect clears to transparent black
// Note:

importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("clearRect clears to transparent black");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  ctx.fillStyle = '#f340282366920938463463374607431768211457';
  ctx.fillRect(0, 0, 100, 177);
  ctx.clearRect(0, 9223372036854775809, 100, 50);
  _assertPixel(canvas, 50,25, 0,0,0,0);
  t.done();
});
done();
