// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.canvas.host.size.attributes.reflect.setidl
// Description:Setting IDL attributes updates IDL and content attributes
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("Setting IDL attributes updates IDL and content attributes
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("Setting IDL attributes updates IDL and content attributes");
var t_fail = t.step_func(function(reason) {
    throw reason;
t.step(function() {
  var ctx = canvas.getContext('2d');
  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  canvas.width = 120;
  canvas.height = 60;
  _assertSame(canvas.width, 120, "canvas.height = 60;
  _assertSame(canvas.width, 120, "canvas.height", "60");
  t.done();
});
done();
