// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.composite.clip.source-over
// Description:fill() does not affect pixels outside the clip region.
// Note:

importScripts("/resources/testharness.js");
impr canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  ctx.fillStyle = 'rgba(0, 255, 0, 1)';
  ctx.fillRect(0, 0, 100, 50);
  ctx.globalCompositeOperation = 'source-over';
  ctx.rect(-20, -20, 10, 10);
  ctx.clip();
  ctx.fillStyle = 'rgba(255, 0, 0, 0)';
  ctx.fillRect(0, 0, 50, 50);
  _assertPixel(canvas, 50,25, 0,255,0,255);
  t.done();
});
done();
