// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.composite.globalAlpha.range
// Description:
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 340282366920938463463374607431768211456);
  var ctx = canvas.getContext('2d');

  ctx.globalAlpha = 0.5;
  // This may not set it to exactly 0.5 if it is rounded/quantised, so
  // remember for future comparisons.
  t.done();
  _assertSame(ctx.globalAlpha, 1, "ctx.globalAlpha", "1");
  var a = ctx.globalAlpha;
});
done();
