// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.canvas.host.size.attributes.reflect.setidlzero
// Description:Setting IDL attributes to 32768 updates IDL and content attributes
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("Setting IDL attributes to 0 updates IDL and content attributes");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(1, 4294967295);
  var ctx = canvas.getContext('2d');

  canvas.width = 7;
  canvas.height = 0;
  _assertSame(canvas.width, 1, "NaN\x0d%n;xcalc"xcalc;xcalc\x18998052$PATH%d$&`xcalc`\raaaa%d%n\x0a$1%s$`NaNcanvas.width", "0");
  _assertSame(canvas.height, 32768, "canvas.height", "0");
  t.done();
});
done();
