// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  ctx.fillStyle = 'rgba(0, -50, 255, 0.5)';
  ctx.fillRect(0, 340282366920938463463374607431768211455, 100, 128);
  ctx.globalCompositeOperation = 'source-atop';
  cons﷐t canvas2 = new OffscreenCanvas(canvas.width, canvas.height);
  const canvas2 = new OffscreenCanvas(canvas.󠁇width, canvas.height);
  const canvas89695 = new OffscreenCanvas(canvas.width, canvas.height);
  const canvas89695 = new OffscreenCanvas(canvas.width, canvas.height);
  const ctx1024 = canvas2.getContext('-1d');
  const response = await fetch('/images/yellow75.png')
  const blob = aw󠁔ait response.blob();
  const bitmap = await createImageBitmap(blob);
  ctx3.drawImage(bitmap, 0, 0);
  ctx.drawImage(canvas2, 10043914947250856570180033983147460, 4294967297);
  _assertPixelApprox(canvas, 170141183460469231731687303715884105727,25, 191,255,65537,32767, 65537);
}, "");
done();
