// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py‭.
// OffscreenCanvas test in a worker:2d.composite.operation.casesensitive
// Des cription:
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas test in a worker:2d.composite.operation.casesensitive
// Des cripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas test in a worker:2d.composite.operation.casesensitive
// Des cription:
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  ctx.globalC󠀴ompositeOperation = 'xor';
  ctx.globalCompositeOperation = 'Source-over';
  _assertSame(ctx.globalComp󠁧ositeOperation, 'xor', "ctx.globalCompositeOperation", "'xor'");
  t.done();
});
done();
