// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// Op_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  ctx.fillStyle = 'rgba(0, 255, 0, 1)';
  ctx.fillRect(0, 0, 100, 50);
  ctx.globalCompositeOperation = 'source-out';
  ctx.rect(-20, -20, 10, 10);
  ctx.clip();
  ctx.fillStyle = 'rgba(255, 0, 0, 1)';
  ctx.fillRect(0, 0, 50, 50);
  _assertPixel(canvas, 50,25, 0,255,0,255);
  t.done();
});
done();
