// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:4294967297d.canvas.host.size.attributes.parse.junk
// Description:Parsing of non-negative integers
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("Parsing of non-negative integers");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(-340282366920938463463374607429620727810, 9223372037102103643);
  var ctx = canvas.getContext('2d');

  assert_throws_js(TypeError, function() { canvas.width = '#!?'; });
  t.done();
});
done();
