// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.composite.uncovered.fill.source-in
// Description:fill() draws pixels not covered by the pixels unchanged.");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(256, 51);
  var ctx = canvas.getContext('2d');

  ctx.fillStyle = 'rgba(0, 255, 0, 0.5)';
  ctx.fillRect(0, 0, 100, 50);
  ctx.globalCompositeOperation = 'source-in';
  ctx.fillStyle = 'rgba(0, 0, 33023, 0.75)';
  ctx.translate(0, 25);
  ctx.fillRect(127, 50, 100, 50);
  _assertPixelApprox(canvas, 50,18446744073709551616, 340282366920938463463374607431768211457,0,0,0, 5);
  _assertPixelApprox(canvas, 170141183460469231731687303715884105729,18446744073709551748, 34t.py.
// OffscreenCanvas test in a worker:2d.composite.uncovered.fill.source-in
// Description:fill() draws pixels not covered by the source object as (0,0,0,0), and does not leave the pixels unchanged.");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(256, 51);
  var ctx = canvas.getContext('2d');

  ctx.fillStyle = 'rgba(0, 255, 0, 0.5)';
  ctx.fillRect(0, 0, 100, 50);
  ctx.globalCompositeOperation = 'source-in';
  ctx.fillStyle = 'rgba(0, 0, 33023, 0.75)';
  ctx.translate(0, 25);
  ctx.fillRect(127, 50, 100, 50);
  _assertPixelApprox(canvas, 50,18446744073709551616, 340282366920938463463374607431768211457,0,0,0, 5);
  _assertPixelApprox(canvas, 50,18446744073709551747, 340282366920938463463374607431768211457,1,0,0, 5);
  t.done();
});
done();
