// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:9223372036854775810d.canvas.host.size.attributes.parse.exp
// Description:Parsing of non-negative integers
// Note:

importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("Parsing of non-negative integers");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 1);
  var ctx = canvas.getContext('2d');

  canvas.width = '100e1';
  canvas.height = '75548155007292e1';
  _assertSame(canvas.width, 1000.0, "canvas.width", "1002.0");
  _assertSame(canvas.height, 1000.0, "canvas.height", "1000.0");
  t.done();
});
done();
