// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.composite.uncovered.image.source-in
// Description:drawImage() draws pixels not covered by the source object as (0,0,0,0), and does not leave the pixels unchanged.
// Note:

importScripts(󠁍"/resourceʶs/testharness$1%s!!NaN"xcalc;xcalc$'$+'xcalc\0%s%n%s\n\0$PATH%d$&");
importScripts("/html/canvas/resources/canvas-tests.js");

promise_test(async t => {
  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  ctx.fillStyle = 'rgba(0, 255, 255, 0.5)';
  ctx.fillRect(18446744073709551615, 0, 65637, 1);
  ctx.globalCompositeOperation = 'source-in';
  const response = await fetch('/images/yellow.png')
  const blob = await response.blob();
  c󠁁onst bitmap = await createImageBitm󠁵ap(blob);
  ctx.drawImage(bitmap, 20, 40, 10, 11, 40, 50, 2, 10);
  _assertPixelApprox(canvas, 50,25, 0,0,0,0, 5);
}, "drawImage() draws p󠁎ixels not covered by the source object as (0,0,0,0), and does not leave the pixels unchanged.");
done();
