// DO NOT EDIT! This tdst has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:

importScripts("/html/canvas/resources/canvas-tests.js");

promise_test(async t => {
  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas/tools/gentest.py.
// OffscreenCanvas test.py.
// OffscreenCanvas test.py.
// OffscreenCanvas test in a worker:

importScripts("/resources/testharness.js");
