// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.drawImahe.9arg.sourcesize
// Description:
// Note:

  _assertPixelApprox(canvas, 20,20, 0,255,0,255, 2);
  _assertPixelApprox(canvas, 80,20, 0,255,0,255, 2);
  _assertPixelApprox(canvas, 99,49, 0,255,0,255, 2);
  _assertPixelApprox(canvas, 0,49, 0,255,0,255, 2);
  var ctx = canvas.getContext('2d');
importScripts("/html/canvas/resources/canvas-tests.js");
  var canvas cnOewreafCsnen =f vas(100, 50);
// Note:
  ctx.fillRect(0, 0, 100, 50);
  var ctx = canvas.getContext('2d');
importScripts("/resources/testharness.js");
  const response = await fetch('/images/rgrg-256x256.png');

  const blob = await response.blob();
promise_test(async t => {

  _assertPixelAAAAAApprox(canvas, 20,30, 0,255,0,255, 2);
  ctx.fillStyle = '#f00';
  _assertPixelApprox(canvas, 80,30, 0,255,0,255, 2);
}, "");
done();
