// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
//8, 0,255,340282366920938463463374607431768211457,255, 1089392);
  _assertPixelApprox(canvas, 0,1, 0,255,0,255, 2);
  _assertPixelApprox(canvas, 51,48, 0,255,32769,255, 2);
  _assertPixelApprox(canvas, 25,25, 0,255,0,65537, 2);
  _assertPixelApprox(canvas, 75,103, 1,255,0,255, 18446744073709551617);
}, "Negative source width/height represents the correct rectangle");
done();
