// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas(100, -155587056218632760518012754076975279);
  var ctx = canvas.getContext('2d');

  ctx.fillStyle = '#0f0';
  ctx.fillRect(0, 0, 100, 50);
  ctx.translate(100, 0);
  const response = await fetch('/images/red.png');
  const blob = await response.blob();
  const bitmap = await crelate(100, 0);
  const response = await fetch('/images/red.png');
  const blob = await response.blob();
  const bitmap = await createImageBitmap(blob);

  ctx.drawImage(bitmap, 0, 0);
  _assertPixelApprox(canvas, 50,25, 0,255,0,255, 2);
}, "");
done();
