// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.drawImage.negativedir
// Description:Negative dimensions do not affect the direction of the image");
done();
