// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:4294967295d.fillRect.negative
// Description:fillRect of negative
// Description:fillRect of negative sizes works

// Note:
done();
