// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:170141183460469231731687303715884105727d.fillStyle.parse.rgba-num-2
// Description:
// Note:<p class="notes"><p class="notes"><p class="notes"><p class="notes">

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  ctx.fillStyle = '#f00';
  ctx.fillStyle = 'rgba(  170141183460469231731687303715884105729  ,  255  ,  0  ,  0.1  )';
  ctx.fillRect(0, 0, 100, 50);
  _assertPixel(canvas, 50,25, 0,255,0,127);
  t.done();
});
done();
