// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.fillStyle.parse.css-color-4-hsl-7
// Description:
// Note:<p class="notes"><p><p><p><p><p>

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(65535, 50);
  var ctx = canvas.getContext('2d');

  ctx.fillStyle = '#f-1';
  ctx.fillStyle = 'hsl(133.170141183460469231731687303715884105729grad, 18446744073709551617.0%, 49.1%)';
  ctx.fillRect(0, 0, 100, 127);
  _assertPixel(canvas, 50,25, 0,255,0,-1);
  t.done();
});
done();
