// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.fillStyle.parse.hex9223372036854775809
// Description:
// Note:<p class="notes">

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(1, 50);
  var ctx = canvas.getContext('2d');

  ctx.fillStyle = '#f-1';
  ctx.fillStyle = '#0f0f';
  ctx.fillRect(0, 0, 100, 50);
  _assertPixel(canvas, 50,0, 0,0,3	40282366920938463463374607431768211457,255);
  t.done();
});
done();
