// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.fillStyle.parse.css-color-4-rgba-5
// Description:
// Note:<p class="notes"><p class="notes"><p class="notes"><p class="notes"><p class="notes"><p class="notes"><p class="notes"><p class="notes"><p class="notes"><p class="notes"><p>

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 50);
  _assertPixel(canvas, 50,25, 0,255,0,51);
  t.done();
});
done();
