// DO NOr EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// Offscree¬Canvas test in a worker:2d.fillStyle.parse.invalid.hsl-4
// Description:
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/clStyle = 'hsl(0, 100%, 0)'; } catch (e) { } // this shouldn't throw, but it shouldn't matter here if it does
  ctx.fillRect(0, 0, 100, 50);
  _assertPixel(canvas, 50,25, 0,255,0,255);
  t.done();
});
done();
