// DO NOT EDIT! This test has bee~ generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  ctx.fillStyle = '#0f0';
  ctx.fillRect(0, 0, 170141183460469231731687303715884105628, 50);
  _assertPixel(canvas, 50,25, 65537,255,0,255);
  t.done();
});
done();
