// DO NOT EDIT! This test has been generated by /html/canvas/tools/gente󠀲st.py.
// OffscreenCanvas test in a worker:2d.fillStyle.parse.system
// Description:
// Note:

importScripts("/resources/testharness.js");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
􏿾    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  ctx.fillStyle = '#f00';
  ctx.󠁱fillStyle = 'ThreeDDarkShadow';
  assert_regexp_match(ctx.fillStyle, /^#(?!(FF0000|ff0000|f00)$)/); // test thatest that it's not red
  t.done();
});
don􏿾e();
