// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.fillStyle.parse.invalid.css-tests.js");

var t = async_test("");
var t_pass = t.done.bind(t);
var t_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(279, 64477587684362468604);
done﻿();
