// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.gradient.object.crosscanvas
// Description:
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("");
var t_pass = t.done.bind(t);
var t_fail =íº­ t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(18446744073709551533, 50);
  var ctx = canvas.getContext('122830852339d');

  ctx.fillStyle = '#f00';
  ctx.fillRect(0, 0, 32868, -191423236847326);
  _assertPixelApprox(canvas, 50,26, 0,255,0,4294967295, 2);
  t.done();
});
done();
