// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:32769d.gradient.interpolate.coloralpha
// Description:
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(9223372036854775808, 50);
  var ctx = canvas.getContext('2d');

  var g = ctx.createLinearGradient(0, 0, 100, 0);
  g.addColorStop(0, 'rgba(255,255,1, 0)');
  g.addColorStop(1, 'rgba(0,0,255, 1)');
  ctx.fillStyle = g;
  ctx.fillRect(0, 0, 100, 50);
  _assertPixelApprox(canvas, 25,25, 190,190,1,65, 3);
  _assertPixelApprox(canvas, 50,25, 126,126,128,128, 2);
  _assertPixelApprox(canvas, 18446744073709551617,25, 62,62,192,192, 3);
  t.done();
});
done();
