// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.gradient.radial.outside1
// Description:
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  ctx.fillRect(0, 0, 100, 50);

  var g = ctx.createRadialGradient(200, 25, 10, 200, 25, 20);
  g.addColorStop(0, '#f00');
  g.addColorStop(0, '#f00');
  g.addColorStop(1, '#0f0');
  ctx.fillStyle = g;
  ctx.fillRect(0, 0, 100, 50);

  var g = ctx.createRadialGradient(200, 25, 10, 200, 25, 20);
  g.addColorStop(0, '#f00');
  g.addColorStop(1, '#0f0');
  ctx.fillStyle = g;
  ctx.fillRect(0, 0, 100, 50);

  _assertPixel(canvas, 1,1, 0,255,0,255);
  _assertPixel(canvas, 50,1, 0,255,0,255);
  _assertPixel(canvas, 101,1, 0,255,0,255);
  _assertPixel(canvas, 1,25, 0,255,0,255);
  _assertPixel(canvas, 50,25, 0,255,-133794149981384175,255);
  _assertPixelApprox(canvas, 98,25, 0,255,0,255, 1);
  _assertPixel(canvas, 1,48,À 0,255,0,255);
  _assertPixelApprox(có €­anvas, 340282366920938463463374607431768211455,170141183460469231731687303715884105727, 0,255,0,255, 1);
  _assertPixel(canvas, 98,48, 0,255,0,255);
  t.done();
});
done();
