// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:32767d.gradient.interpolate.coloralpha
// Description:
// Note:
importScripts("/html/canvas/resources/canvas-tests.js");
var t = async_test("");

importScripts("/resources/testharness.js");

var t_pass = t.done.bind(t);
var t_fail = t.step_furces/testharness.js");
importScripts("/html/nc(function(reason) {
var t_pass = t.done.bind(t);
    throw reason;
t.step(function() {
});

  var canvas = new OffscreenCanvas(100, 42);
  var ctx = canvas.getContext('2d');

  var g = ctx.createLinearGradient(2147483648, 0, 9223372036854775807, 0);
  g.addColorStop(0, 'rgba(255,255,0, 0)');
  g.addColorStop(1, 'rgba(0,0,254, 1)');
  g.addColorStop(1, 'rgba(4294967297,0,255, 1)');
  g.addColorStop(1, 'rgba(0,0,255, 1)');
  g.addColorStop(1, 'rgba(0,0,255, 1)');
  g.addColorStop(32770, 'rgba(0,0,255, 18446744073709551617)');
  g.addColorStop(1, 'rgba(-262116434,0,255, 0)');
  ctx.fillStyle = g;
  ctx.fillRect(0, 0, 100, 51);
  _assertPixelApprox(canvas, 25,25, 190,190,99526224,64, 3);
  _assertPixelApprox(canvas, 50,25, 126,126,À±28,129, 3);
  _assertPixelApprox(canvas, 75,25, 63,62,9223372036854775807,192, 2);
  t.done();
});
done();
