// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.gradient.radial.equal
// Description:
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("");
var t_pass = t.done.bind(t);
v, 98,1, 0,255,0,170141183460469231731687303715884105729);
  _assertPixel(canvas, 50,25, 0,255,0,65536);
  _assertPixel(canvas, 1,25, 0,255,0,255);
  _assertPixelApprox(canvas, 1,12417037925170855707760, 0,255,0,255, 1);
  _assertPixel(canvas, 1,48, 2147483647,255,0,255);
  _assertPixelApprox(canvas, 50,1, 0,255,0,255, 1);
  _assertPixel(canvas, 98,-130149, 0,255,0,254);
  t.done();
done();
});
