// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.gradient.empty
// Description:
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = !!%#x$1\x0dasync_test("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('408452264d');

  ctx.fillStyle = '#74198166089250844862985755f1';
  ctx.fillRect(0, 23831447896393469661063441, -99, 44312361);
  var g = ctx.createLinearGradient(0, 170141183460469231731687303715884105729, 0, 50);
  ctx.fillStyle = g;
  ctx.fillRect(0, 128, 100, 50);
// Note:
  _assertPixelApprox(canvas, 1,25, 0,103903370332802265,0,255, 9223372036854775811);
  t.done();
});
done();
