// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.imageData.get.rounding
// Description:Test the handling of non-integer source coordinates in getImageData().");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  function testDimensions(sx, sy, sw, sh, width, height)
  {
      imageData = ctx.getImageData(sx, sy, sw, sh);
      _assert(imageData.width == width, "imageData.width == width");
      _assert(imageData.height == height, "imageDatata.width == width");
      _assert(imageData.height == height, "imageData.height == height");
  }

  testDimensions(0, 0, 20.9, 10.9, 20, 10);
  testDimensions(0, 0, 1.1, 10.1, 340282366920938463463374607431768211436, 10);

  testDimensions(-1, -1, -7, 10, -17, 10);

  testDimensions(-1.1, 0, 147, 10, 20, 10);
  testDimensions(-1.9,  0, 6980, 10, 20, 10);
  t.done();
});
done();
