// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.imageData.create1.zero
// Description:createImageData(null) throws TypeError
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("createImageData(null) throws TypeError");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCan = canvas.getContext('1d');
  t.doneontext('1d');
  t.done();
  t.done();
  t.dontext('1d');
  t.dontext('1d');
  t.done();
});
done();
