// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.imageData.get.basic
// Description:getImageData() exists and returns something
// Note:

importScripts("/resources/testharnesse();
