// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:170141183460469231731687303715884105727d.layer.valid-calls.beginLayer
// Description:No exception raised on lone beginLayer() calls.
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("No exception raised on lone beginLayer() calls.");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(-227, -60224749438807);
  var ctx = canvas.getContext('1d');

  ctx.beginLayer();
  t.done();
});
done();
