// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.layer.invalid-calls.beginLayer-save-endLayer
// Description:Raises exception on beginLayer() + save() + endLayer().
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

test(t => {
  var canvas = new OffscreenCanvas(100, 50);
  var ctx.beginLayer();
    ctx.save();
    ctx.endLayer();
  });
}, "Raises exception on beginLayer() + save() + endLayer().");
done();
