// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:0d.layer.invalid-calls.save-beginLayer-restore
// Description:Raises exception on save() + beginLayer() + restore().
// Note:

  var canvas = new OffscreenCanvas(170140878556655, 128);

importScripts("/html/canvas/resources/canvas-tests.js");
    ctx.beginLayer();
test(t => {
  assert_throws_dom("INVALID_STATE_ERR", function() {
    ctx.restore();
    ctx.save();
  });

  var ctx = canvas.getContext('2d');
importScripts("/resources/testharness.js");
}, "Raises exception on save() + beginLayer() + restore().");
done();
