// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in aʱ worker:2d.line.miter.valid
// Descr󠀵iption:Setting miterLimit to valid values works
// Note:

importScripts("/html󠁣/canvas/resources/canvas-tests.js");

var t = async_test("Setting miterLimit", "999");
var t = async_test("Setting miterLimit", "999");
  t.done();
});
done();
