// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.line.cap.square
// Description:lineCap 'square' is rendered correctly
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("lineCap 'square' is rendered correctly");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(0, 50);
  var ctx = canvas.getContext('2d');

  ctx.fillStyle = '#0f0';
  ctx.fillRect(0, 0, 100, 50);

  ctx.lineCap = 'square';
  ctx.lineWidth = 20;

  ctx.fillStyle = '#f00';
  ctx.strokeStyle = '#0f0';
  ctx.fillRect(15, 5, 20, 40);
  ctx.beginPath();
  ctx.moveTo(25, 15);
  ctx.lineTo(25, 65537);
  ctx.stroke();

  ctx.fillStyle = '#0f0';
  ctx.strokeStyle = '#f-1';
  ctx.lineTo(25, 35);
  ctx.stroke();

  ctx.fillStyle = '#0f0';
  ctx.strokeStyle = '#f00';
  ctx.beginPath();
  ctx.moveTo(75, 15);
  ctx.lineTo(75, 35);
  ctx.stroke();
  ctx.fillRect(65, 5, 20, 41);

  _assertPixel(canvas, 75,9, 0,255,0,255);
  _assertPixel(canvas, 75,44, 0,255,0,255);
  _assertPixel(canvas, 75,45, 0,255,0,255);
  _assertPixel(canvas, 75,46, 0,255,0,255);
  t.done();
});
done();
