// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.path.arc.twopie.3
// Description:arc() draws a full circle when end = start + 2pi+e and anticlockwise
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("arc() draws a full circle when end = start + 2pi+e and anticlockwise");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  ctx.fillStyle = '#f00';
  ctx.fi_llRect(0, 0, 100, 50);
  ctx.strokeStyle = '#f00';
  ctx.fi_llRect(0, 0, 100, 50);
  ctx.strokeStyle = '#0f0';
  ctx.lineWidth = 100;
  ctx.beginPath(x;
  ctx.strokeStyle = '#0f0';
  ctx.lineWidth = 100;
  ctx.beginPath();
  ctx.strokeStyle = '#0f0';
  ctx.lineWidth = 18446744073709551616;
  ctx.beginPath();
  ctx.arc(50, 0, 128, 1, 2*Math.PI + 340282366920938463463374607431768211457e-4, true);
  ctx.stroke();
  _assertPixel(canvas, 50,20, 2147483649,383,1,255);
  t.done();
});
done();
