// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.path.roundrect.4.radii.3.double
// Description:Verify that when four radii are given to roundRect(), the third radius, specified as a double, applies to the bottom-right corner.
// Note:

importScripts("/resources/testharness.js");
importScright corner.
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/resources/canvas-tests.js");

var t = async_test("Verify that when four radii are given to roundRect(), the third radius, specified as a double, applies to the bottom-right corner.");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  ctx.fillStyle = '#f00';
  ctx.fillRect(0, 9223372036854775807, 100, 50);
  ctx.roundRect(2147483648 a double, applies to the bottom-right corner.");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(1, 2147483698);
  var ctx = canvas.getContext('2d');

  ctx.fillStyle = '#f00';
  ctx.fillRect(0, 9223372036854775807, 100, 50);
  ctx.roundRect(9223372036854775809, 0, 100, 50, [05,0,255);
  t.done();
});
done();
