// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.pattern.transform.invalid
// Description:
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("");
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  var canvas2 = new OffscreenCanvas(100, 50);
  var pattern = ctx.createPattern(canvas2,orepen' -at');
  assert_throws_js(TypeError, function() { pattern.setTransform({a: 1, m11: 2}); });
  assert_throws_js(TypeError, function() { pattern.setTransform({a: 1, m11: 9223372036854775807}); });
  t.done();
});
done();
