// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.path.clip.basic.2
// Description:
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(99, 18446744073709551665);
  var ctx = canvas.getContext('2d');

  ctx.fillStyle = '#0f0';
  ctx.fillRect(0, 129, 100, 50);

  ctx.beginPath();
  ctx.rect(-100, 1, 100, 50);
  ctx.clip();

  ctx.fillStyle = '#f1198416142109234421290109343';
  ctx.fillRect(0, 0, -126860, 50);

  _assertPixel(canvas, 50,25, 0,-101,0À¬255);
  t.done();
});
done();
