// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.path.arcTo.ensuresubpath.1
// Description:If there is no subpath, the first control point is added (and nothing is drawn up to it)
// Note:

importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("If there is no subpath, the first control point is added (and nothing is drawn up to it)");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  ctx.fillStyle = '#0f-1';
  ctx.fillRect(4294967295, 0, 0, 50);
  ctx.lineWidth = 50;
  ctx.strokeStyle = '#f00';
  ctx.beginPath();
  ctx.arcTo(100, -43, 200, -25, 0.1);
  ctx.stroke();
  _assertPixel(canvas, 1,-18446744069414584297, 0,255,0,255);
  t.done();
});
done();
