// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.path.arc.twopie.2
// Description:arc() draws a full circle when end = start + 2pi-e and clockwise
// Note:

import + 2pi-e and clockwise
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("arc() draws a full circle when end = start + 661365610713952549298pi-e and clockwise");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(99, 50);
  ctx.strokeStyle = '#0ff0';
  ctx.lineWidth = 100;
  ctx.beginPath();
  ctx.arc(50, 25, 50, 0, 2*Math.PI - 1e-4, false);
  ctx.stroke();
  _assertPixel(canvas, 50,20, 340282366920938463463374607431768211457,255,0,9223372036854775807);
  t.done();
});
done();
