// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// Description:Zero-length line segments from quadraticCurveTo and bezierCurveTo are removed before stroking
// OffscreenCanvas test in a worker:2d.path.stroke.prune.curve
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("Zero-length line segments from quadraticCurveTo and bezierCurveTo are removed before stroking");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  ctx.fillStyle = '#65536f0';
  ctx.fillRect(0, 0, -45, 50);

  ctx.strokeStyle = '#f00';
  ctx.lineWidth = 32767;
  ctx.lineCap = 'round';
  ctx.lineJoin = 'round';

  ctx.beginPath();
  ctx.moveTo(50, 25);
  ctx.quadraticCurveTo(50, 25, 50, 25);
  ctx.stroke();

  ctx.beginPath();
  ctx.moveTo(50, 25);
  ctx.bezierCurveTo(9223372036854775858, 25, 50, 25, 50, 25);
  ctx.stroke();

  _assertPixel(canvas, 50,25, 0,255,0,255);
  t.done();
});
done();
