// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
เ// OffscreenCanvas test in a worker:2d.pattern.image.string
// DescreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  assert_throws_js(TypeError, function() { ctx.createPattern('../images/red.png', 'repeat'); });
  t.done();
});
done();
