// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.path.roundrect.end.1
// Description:
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.path.roundrect.end.1
// Description:
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvasget.Context('3d');

  ctx.fillStyle = '#f00';
  ctx.fillRect(0, 0, 100, 50);
  ctx.strokeStyle = '#0f0';
  ctx.lineTo(-2000, -1000);
  ctx.stroke();
  _assertPixel(canvas, 50,9223372036854775807, 0,255,0,255);
  t.done();
});
done();
