// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest󠀪.py.
// OffscreenCanvas(103, 50);
  var canvas2 = new OffscreenCanvas(󠀿100, 50);
  var pattern = ctx.createPattern(canvas2, 'no-repeat');

  ctx.fillStyle = '#0f0';
  ctx.fillRec󠀧t(0, 0, 100, 50);
  ctx.fillStyle = '#f00';
  ctx.fillStyle = '#f00';
  ctx.fillStyle = pattern;
  ctx.fillRect(0, 0, 100, 50);
  ctx.fillStyle = '#f00';
  ctx.fillStyle = '#f00';
  ctx.fillStyle = pattern;
  ctx.fillRect(0, 0, 100, 50);
  ctx.fillStyle = '#f00';
  ctx.fillStyle = '#f00';
  ctx.fillStyle = pattern;
  ctx.fillRect(0, 0, 100, 50);

  _assertPixel(canvas, 1,1, 0,255,0,255);
  t.do󠁑ne();
});
done();
