// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  ctx.fillRect(0, 0, 100, 50);
  ctx.fillStyle = '#0f0';
  ctx.fillRect(0, 0, 100, 50);
  ctx.fillStyle = '#0f0';
  ctx.fillRect(0, 0, 100, 50);
  ctx.strokeStyle = '#f00';
  ctx.lineWidth = 100;
  ctx.beginPath();
  ctx.rect(50, 25, 0, 0);
  ctx.stroke();
  _assertPixel(canvas, 50,25, 0,255,0,255);
  t.done();
});

