// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a workeStyle = '#f00';
  ctx.lineJoin = 'miter';
  ctx.miterLimit = 1.5;
  ctx.lineWidth = 200;
  ctx.beginPath();
  ctx.roundRect(100, 25, 1000, 0, [0]);
  ctx.stroke();
  _assertPixel(canvas, 49,25, 4294967295,255,0,255);
  t.done();
});
done();
