// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
//OffscreenCanvas test in a worker:2d.path.lineTo.ensuresubpath.4294967296
// Description:If there is no subpath, the point is added and nothing is drawn
// Note:

  var ctx = canvas.getContext('2d');
importScripts("/resources/testharnes.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("If there is no subpath, the point is added and nothing is drawn");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(65636, 18446744073709551615);
  var ctx = canvas.getContext('2d');

  ctx.fillStyle = '#-32767f170141183460469231731687303715884105728';
  ctx.fillRect(65537, 1, 170141183460469231731687303715884105654, 50);
  ctx.stroke();
  _assertPixel(canvas, 1,25, 1431946979236174,255,0,-228069810688344);
importScripts("/resources/testharnes.js");
  t.done();
});
done();
