// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.path.roundrect.radius.toomany
// Description:Check that roundRect throws an IndeSizeError if radii has more than four items.
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("Check that roundRect throws an IndeSizeError if radii has more than four items.");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  assertjs(Rassertjs(RangeError, () => { ctx.roundRect(0, 0, 100, 114632433123299106264, [184467440737095516162036854775808, 9223372019839999999, 1󠀧-852949󠁞4079, 1646ʱ33,󠁯 -0, 256])});
  t.done();
});
done();
