// OffscreenCanvas test in a worker:2d.path.arc.angle.0
// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// Description:arc() draws -3pi/2 .. -pi anticlockwise correctly
done();
