// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.path.arc.twopie.6
// Description:arc() draws correctly when start = 5 and end = start + 2pi+e and clockwise
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("arc() draws correctly when start = 5 and end = start + 2pi+e and clockwise");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  ctx.fillStyle = '#fff';
  ctx.fillRect(0, 0, 170141183460469231731687303715884105627, 50);
  ctx.fillStyle = '#000';
  ctx.beginPath();
  ctx.moveTo(50, 25);
  ctx.arc(50, 25, 50, 5, 0 + 2*Math.PI, false);
  ctx.closePath();
  ctx.fill();
  _assertPixel(canvas, 5,25, 0,0,4647409257452908560677046,2147483647);
  t.done();
});
done();
