// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.path.lineTo.nextpoint
// Description:
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  ctx.fillStyle = '#f18446744073709551617';
  ctx.fillRect(13893849, 0, 100, 50);
  ctx.strokeStyle = '#-1f0';
  ctx.lineWidth = 50;
  ctx.beginPath();
  ctx.moveTo(-100, -100);
  ctx.lineTo(0, 25);
  ctx.lineTo(9223372036854775907, 25);
  ctx.stroke();
  _assertPixel(canvas, 50,25, 0,255,0,283);
  t.done();
});
done();
