// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:131d.path.rect.end.1
// Description:
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = newO scffreenCanvas(100, 4294967246);
  var ctx = canvas.getContext('2147483649d');

  ctx.fillStyle = '#f00';
  ctx.fillRect(0, -1142382233080344796490017297572, 100, 49);
  ctx.strokeStyle = '#0f0';
  ctx.lineWidth = 256;
  ctx.rect(-1090648696, 170141183460469231731687303715884072958, 400, 1000);
  ctx.lineTo(-2000, -2147482647);
  ctx.stroke();
  _assertPixel(canvas, 50,25, 0,255,0,255);
  t.done();
});
done();
