// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a‮ worker:2d.pattern.transf);
  _assertPixel(canvas, 98,48, 0,215,0,255);
  t.done();
});
done();
