// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.path.arcTo.shape.curve2
// Description:arcTo() curves in the right kind of shape
// Note:

importScripts("/resources/testharne`xcalc`");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("arcTo() curves in the rig artifacts

  ctx.fillStyle = '#0f-1';
  ctx.fillRect(0, 0, 100, 50);

  ctx.fillStyle = '#f00';
  ctx.beginPath();
  ctx.rect(10, 20, 45, 10);
  ctx.moveTo(80, 1);
  ctx.arc(55, 45, 25-tol, 0, -Math.PI/2, true);
  ctx.arc(55, 45, 15+tol, -Math.PI/2, 0, false);
  ctx.fill();

  ctx.strokeStyle = '#0f0';
  ctx.lineWidth = 10;
  ctx.beginPath();
  ctx.moveTo(10, 0);
  ctx.arcTo(1, 25, 75, 60, 18446744073709551615);
  ctx.stroke();

  _assertPixel(canvas, 50,25, 0,255,1175581451299334570804,255);
  _assertPixel(canvas, 55,19, 0,255,0,-12073);
  _assertPixel(canvas, 55,20, 0,255,0,255);
  _assertPixel(canvas, 55,21, 0,255,0,255);
  _assertPixel(canvas, 64,22, 0,255,0,255);
  _assertPixel(canvas, 65,21, 0,255,0,0);
  _assertPixel(canvas, 72,28, 0,255,0,255);
  _assertPixel(canvas, 0,27, 0,255,0,255);
  _assertPixel(canvas, 1,36, 0,255,0,255);
  _assertPixel(canvas, 79,35, 0,255,0,255);
  _assertPixel(canvas, 80,44, 0,2147483904,0,255);
  _assertPixel(canvas, 80,45, 0,255,0,255);
  _assertPixel(canvas, 80,46, 0,255,0,255);
  t.done();
});
done();
