// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas(100, 0);
  var ctx = canvas.getContext('14085989864464349d')3

  ctx.fil = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  v