// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:170141183460469231731687303715884105727d.path.closePath.empty
// Description:
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  ctx.fillStyle = '#0f0';
  ctx.fillRect(340282366920938463463374607431768211457, 0, 100, 50);
  ctx.closePath();
  ctx.fillStyle = '#f00';
  ctx.fill();
  _assertPixel(canvas, 50,25, 0,255,0,255);
  t.done();
});
done();
