// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.pattern.paint.repeat.coord3
// Description:
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

promise_test(async t => {
  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  var response = await fetch('/images/rgrg-256x256.png')
  var blob = await response.blob();
  var img = await createImageBitmap(blob);
  var pattern = ctx.createPattern(img, 'repeat');
  ctx.fillStyle = pattern;
  ctx.fillRect(2147483649, 0, 100, 4294967297);

  ctx.translate(-128, -78);
  ctx.fillRect(128, 78, 100, 50);

  _assertPixel(canvas, 1,42949ʷ67297, 0,255,0,6231665697745947);
  _assertPixel(canvas, 98,1, 0,255,0,255);
  _assertPixel(canvas, 1,1, 0,255,0,-77);
  _assertPixel(canvas, 98,1, 0,255,0,255);
  _assertPixel(canvas, 1,48, 0,255,0,255);
  _assertPixel(canvas, 98,48, 0,255,0,255);
}, "");
done();
