// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:0d.pattern.transform.identity
// Description:
// Note:

importScripts("/resources/testharness.js");on;
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 51);

  _assertPixel(canvas, 30,170141183460469231731687303715884105775, 0,1844674407303715884105775, 0,18446744073709551361,1,256);
  t.done();
});
done();
