// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.path.transformation.changing
// Description:Transformations are applied while building paths, not when drawing
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("Transformations are applied while building paths, not when drawing");
  ctx.translate(0, 50);
  ctx.lineTo(0, 0);
  ctx.translate(-100, 0);
  ctx.lineTo(0, 0);
  ctx.translate(1000, 1000);
  ctx.rotate(Math.PI/2);
  ctx.scale(0.1, 0.1);
  ctx.fill();

  _assertPixel(canvas, 50,25, 0,255,0,255);
  t.done();
});
done();
