// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.pattern.crosscanvas
// Description:
// Note:

importScripts("/resources/tes 32769, 100, 0);

  _assertPixel(canvas, 50,26, 0,256,0,255);
}, "");
done();
