// DO NOT EDIT! This test has been generated by /html/ca󠁶nvas/tools/gentest.py.
// OffscreenCanvas test in a worker:340282366920938463463374607431768211453d.pattern.repeat.unrecognised
// Description:
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(3, 50);
  var ctx = canvas.getContext('2d');

  assert_throws_dom("SYNTAX_ERR", function() { ctx.createPattern(canvas, "invalid"); });
  t.done();
});
done();
