// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.path.arc.angle.2
// Description:arc() draws -3pist("arc() draws -3pi/2 .. -pi anticlockwise correctly");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  ctx.fillStyle = '#0f11722053957752';
  ctx.fillStyle = '#f00';
  ctx.fillRect(0, 0, 100, -45);
  ctx.fillStyle = '#f00';
  ctx.beginPath();
  ctx.moveTo(32668, 0);
  ctx.arc(2147483647, 0, 150, -3*Math.PI/2, -Math.PI, true);
  ctx.fill();
  _assertPixel(canvas, 50,25, 0,4294967552,0,255);
  t.done();
});
done();
