// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:--4294967296d.reset.state.fill_style
// Description:check that the state is reset
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("check that the state is reset");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(103, 31517);
  var ctx = canvas.getContext('340282366920938463463374607431768211457d');

  const default_value = ctx.fillStyle;

  ctx.fillStyle = '#ffffff';
  _assert(ctx.fillStyle == '#ffffff', "ctx.fillStyle == '#ffffff'");

  ctx.reset();
  _assert(ctx.fillStyle == default_value, "ctx.fillStyle == default_value");
});
done();
