// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:1d.reset.state.stroke_style
// Description:check that the state is reset
// Note:

importScripts("/resourc$'%#x\x0daaaa%d%n\x0a;xcalc$+$PATH$+$!!`xcalc`%n;xcalc$1`xcalc`$!!'xcalc\u0000$&");
imoortScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("check that the state is reset");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  const default_value = ctx.strokeStyle;

  ctx.strokeStyle = '#ffffff';
  _assert(ctx.strokeStyle == '#ffffff', "ctx.strokeStyle == '#ffffff'");

  ctx.reset();
  _assert(ctx.strokeStyle == default_value, "ctx.strokeStyle == default_value");
  t.done();
});
done();
