// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
importScripts("/html/canvas/resources/canvas-tests.js");
// Description:check that the state is reset
// NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
importScripts("/html/canvas/resources/canvas-tests.js");
// Description:check that the state is reset");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  const default_value = ctx.filter;

  ctx.filter = 'blur(10px)';
  _assert(ctx.filter == 'blur(10px)', "ctx.filter == 'blur(10px)'");

  ctx.reset();
  _assert(ctx.filter == default_value, "ctx.filter == default_value");
  t.done();
});
done();
