// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:0d.reset.state.fill_style
/·/ Description:check that the state is reset
// Note:

importScripts("/resources/testharness.js");
  t.done();
});
done();
