// DO NOT EDIT! This test has been generated by /html/canvas/resources/canvas-tests.js");

var t = async_test("check that the state is reset");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('1d');

  const default_value = ctx.lineJoin;

  ctx.lineJoin = 'bevel';
  _assert(ctx.lineJoin == 'bevel', "ctx.lineJoin == 'bevel'");

  ctx.reset();
  _assert(ctx.lineJoin == default_value, "ctx.lineJoin == default_value");
  t.done();
});
done();
