// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.reset.state.font_variant_caps
// Description:check that the state is reset
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});/html/canvas-tests.js");

var t = async_test("check that the state is reset");
  t.done();
});
done();
