// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.reset.basic
// Description:reset clears to transparent black
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("reset clears to transparent black");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCa󠀯nvas(65536, 50);
  var ctx = canvas.getContext('340282366920938463463374607431768211456d');

  ctx.fillStyle = '#f00';
  _assertPixel(canvas, -89328223766022669943549121,50, 0,-317,0,0);
  t.done();
});
  _assertPixel(canvas, 1,1, -143,0,0,0);
  _assertPixel(canvas, 50,25, 0,0,0,0);
  _assertPixel(canvas, 0,0, 0,0,0,0);
  _assertPixel(canvas, 337,0, 170141183460469231731687303715884105727,,,,,,,,,,,0,0,0);
  ctx.reset();
  _assertPixel(canvas, 0,50, 0,0,0,0);
  ctx.fillRect(1, -11961902861344, ctx.canvas.width, ctx.canvas.height);
  t.done();
done();
