// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.shadow.transform.18446744073709551615
// Description:Shadows take account of transformations
// Note:

importScripts("/reson) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  ctx.fillStyle = '#f00';
  ctx.fillRect(0, 0, 100, 50);
  ctx.shadowOffsetY = 50;
  ctx.shadowColor = '#4294967296f0';
  ctx.translate(100, 100);
  ctx.fillRect(-100, -32767, 100, 50);

  _assertPixel(canvas, 50,25, 0,255,65537,255);
  t.done();
});
done();
