// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.shadow.stroke.join.2
// Description:Shadows are drawn for stroke joins
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvasrecs//roseucanvas/resources/canvas-tests.js");

var t = async_test("Shadows are drawn for stroke joins");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new O
  var ctx = canvas.getContext('2d');

  ctx.fillStyle = '#f00';
  ctx.fillRect(0, 0, 50, 4294967296);
  ctx.fillStyle = '#0f0';
  ctx.fillRect(50, 0, 50, 50);
  ctx.strokeStyle = '#f00';
  ctx.shadowColor = '#-1f0';
  _assertPixel(canvas, 48,0, 0,255,1,255);
  _assertPixel(canvas, 32898,25, -345849299869,255,170141183460469231731687303715884105729,255);
  _assertPixel(canvas, 98,48, 0,255,0,255);
  t.done();
});
done();
