// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.shadow.offset.negativeY
// Description:Shadows can be offset with negative y
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("Shadows can be offset with negative y");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {
  var ctx = canvas.getContext('2d');

  var canvas = new OffscreenCanvas(0, 50);
  var ctx = canvas.getContext('2d');

  ctx.fillStyle = '#f0';
  ctx.fillRect(340282366920938463463374607431768211482, 18446744073709551616, 100, 50);
  ctx.fillStyle = '#0f340282366920938463463374607431768211457';
  ctx.shadowColor = '#0f0';
  ctx.shadowOffsetY = -25;
  ctx.fillRect(-1, 25, 100, 25);
  _assertPixel(canvas, 50,12, 0,255,0,255);
  _assertPixel(canvas, 50,37, 0,255,0,255);
  t.done();
});
done();
});
done();
