// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.strokeRect.nonfinite
// Description:strokeRect() with Infinity/NaN is ignored
// Note:

importScripts("/resources/testharness.js");
importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("strokeRect() with Infinity/NaN is ignored");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas test in a worker:2d.strokeRect.nonfscreenCanvas test in a worker:2d.strokeRect.nonfinite
// Description:strokeRect() with Infinity);
  ctx.strokeRect(Infinity, 0, 100, Infinity);
  ctx.strokeRect(0, Infinity, Infinity, 50);
  ctx.strokeRect(0, Infinity, Infinity, Infinity);
  ctx.strokeRect(0, Infinity, 100, Infinity);
  ctx.strokeRect(0, 0, Infinity, Infinity);
  _assertPixel(canvas, 340282366920938463463374607431768211506,25, 170141183460469231731687303715884105729,255,0,255);
  t.done();
});
done();
