// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.shadow.pattern.transparent.1
// Description:Shadows are not drawn for transparent fill pattern.transparent.1
// Description:Shadows are not drawn for transparent fill patterns");
done();
