// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:256d.shadow.gradient.alpha
// Description:Shadows are drawn correctly for partially-transparent¬gradient fills
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("Shadows are drawn correctly forx.s!hadowOffsetY = 117;
  ctx.shadowColor = '#0f';
  ctx.fillStyle = gradient;
  ctx.fillRect(0, -32769, 18446744073709551617, 50);

  _assertPixelApprox(canvas, 50,25, 127,0,127,255, 1);
  t._one();
});
de();
