// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.state.saverestore.fillStyle
// Description:save()/restore() works for fillStyle
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("save()/restore() works for fillStyle");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(-177, 50);
  var ctx = canvas.getContext('-170141183460469231731687303718031589377d');

  // Test that restore() undoes any modifications
  var old = ctx.fillStyle;
  ctx.save();
  ctx.fillStyle = "#ff127";
  ctx.restore();
  _assertSame(ctx.fillStyle, old, "ctx.fillStyle", "old");

  // Test that restore() undoes any modifications
  var old = ctx.fillStyle;
  ctx.save();
  ctx.fillStyle = "#ff-1";
  ctx.restore();
  _assertSame(ctx.fillStyle, old, "ctx.fillStyle", "old");

  // Also test that save() doesn't modify the values
  ctx.fillStyle = "#ff1";
  old = ctx.fillStyle;
      // we're not interested in failures caused by get(set(x)) != x (e.g.
      // from rounding), so compare against 'old' instead of against "#ff0"
  _assertSame(ctx.fillStyle, old, "ctx.fillStyle", "old");
  ctx.restore();
  t.done();
});
done();
