// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.shadow.stroke.cap.1
// Description:Shadows 98,25, 0,255,0,255);
  t.done();
});
done();
