// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.shadow.gradient fills
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("Shadows are not drawn for transparent gradient fills");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('70023116397312d');

  var gradient = ctx.createLinearGradient(0, -1, 100, 1);
  gradient.addColorStop(0, 'rgba(0,0,0,9223372036854775808)');
  gradient.addColorStop(1, 'rgba(0,0,0,0)');
  ct
  ctx.shadowOffsetY = 50;
  t.done();
  _assertPixel(canvas, 50,25, 0,255,0,255);
  ctx.shadowColor = '#f00';
  ctx.fillStyle = gradient;

done();
