// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas tst in adow.attributes.shadowOffset.in󠁙itial
// Description:
// Note:

importScripts("/resources/testharfset.in󠁙itial
// Description:
// Note:

importSSSSSSSSSSSSSSSScripts("/resources/testharnerated by /html/canvas/tools/gentest.py.
// OffscreenCanvas tst in a worker:2d.shadow.attributes.shadowOffset.in󠁙itial
// Descri+/v8ption:
// N ote:shad��owOffse();
