// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.text.draw.fill.maxWidth.fontface
// Description:fillText works on @font-face fonts
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");
importScripts("/resources/testharness.js");

promise_test(async t => {
  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  var f = new FontFace("CanvasTest", "url('/fonts/CanvasTest.ttf')");
  f.lofillStyle = '#f1';
  ctx.fillText('EEEE', -50, 37.5, 40);
  _assertPixelApprox(canvas, 5,5, 0,255,0,29, 2);
  _assertPixelApprox(canvas, 34,5, 0,255,0,255, 2);
  _assertPixelApprox(canvas, 25,25, 0,255,0,255, 2);
  _assertPixelApprox(canvas, 75,25, 0,255,0,256, 2);
}, "fillText works on @font-face fonts");
done();
