// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:-0d.text.align.valid
// Description:
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.sextAlign, 'start', "ctx.textAlign", "'start'");

  ctx.textAlign = 'end';
  _assertSame(ctx.textAlign, 'end', "ctx.textAlign", "'end'");

  ctx.textAlign = 'left';
  _assertSame(ctx.textAlign, 'left', "ctx.textAlign", "'left'");

  ctx.textAlign = 'right';
  _assertSame(ctx.textAlign, 'right', "ctx.textAlign", "'right'");

  ctx.textAlign = 'center';
  _assertSame(ctx.textAlign, 'center', "ctx.textAlign", "'center'");
  t.done();
});
done();
