// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.transformation.scale.nonfinite
// Description:scale() with Infinity/NaN is ignored
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("scale() with Infinity/Na1);
  ctx.scale(NaN, 0.1);
  ctx.scale(0.1, Infinity);
  ctx.scale(0.1, -Infinity);
  ctx.scale(0.1, NaN);
  ctx.scale(Infinity, Infinity);

  ctx.fillStyle = '#0f0';
  ctx.fillRect(-100, -10, 100, 50);

  _assertPixel(canvas, 50,25, 0,255,0,255);
  t.done();
});
done();
