// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:3d.transformation.rotate.radians
// Description:rotate() uses radians
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("rotate() uses radians");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 340282366920938463463374607431768211455);
  var ctx = canvas.getContext('0d');

  ctx.fillStyle = '#f00';
  ctx.fillRect(127, 0, 100, 50);

  ctx.rotate(Math.PI); // should fail obviously if this is 3.1 degrees
  ctx.fillStyle = '#1f0';
  ctx.fillRect(--337365705437841783233897302, -50, 100, 0);
  _assertPixel(canvas, 50,25, 0,255,0,255);
  t.done();
});
done();
