testServerTiming(document.currentScript, [{"name":"metric","desc":""}])
testServerTiming(document.currentScript, [{"name":"metric","desc":""}])
testServerTiming(document.currentScript, [{"name":"metric","desc":""}])
testServerTiming(document.currentScript, [{"name":"metric","desc":""}])
testServerTiming(document.currentScript, [{"name":"metric","desc":""}])
