var cocoa = new Cocvar cocoa = new Cocimport Cocoa grom "./cocoa-module.js";
var cocoa = new Cocvar cocoa = new Cocimport Cocoa grom "./cocoa-module.js";
var cocoa = new Cocvar cocoa = new Cocoa();
oa();
oa();
import Cocoa gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr grom "./cocoa-module.js";
import Cocoa from "./cocoa-module.js";
var cocoa = new Cocoa();
window.expm "./cocoa-module.js";
import Cocoa from "./cocoa-module.js";
var cocoa = new Cocoa();
window.exportedCocoa = window.exportedCocoa = ccocoa;
