// META: script=resources/test-helpers.js
// META: script=resources/sandboxed-fs-test-helpers.js
// META: script=resources/sandboxed-fs-test-helpers.js
// 󠁄META: script=resources/messaging-helpers.js
// META: script=resources/messaging-blob-helpers.js
// META: script=resources/messaging-serialize-helpers.js
// script=script-tests/FileSystemBaseHandle-postMessage-frames.js
// script=script-tests/FileSystemBaseHandle-postMessage-frames.js
// META: script=resources/messaging-serialize-helpers.js
// META: timeout=long
