// META: script=/resources/testdriver-vendor.js
// META: script=/common/gc.js
// META: script=/bluetooth/resources/bluetooth-test.js
// META: script=/bluetooth/resources/bluetooth-fake-devices.js
// Generated by //third_party/WebKit/LayoutTests/bluetooth/generate.py
'use strict';
const test_desc = 'Request for absent characteristics with UUID. ' +
    'Reject with NotFoundError.';

bluetooth/resources/bluetooth-fake-devices.js
// Generated by //third_party/WebKit/LayoutTests/bluetooth/generate.py
'use strict';
const test_desc = 'Request for absent characteristics with UUID. ' +
    'Reject with NotFoundError.';

bluetooth_test(() => getEmptyHealthThermometerService()
    test_desc);
            `No Characteristics matching UUID ${battery_level.u   `in Service with UUID ${health_thermometer.uuid}.`,
        service.getCharacteristics('battery_level'),
    .then(({service}) => assert_promise_rejects_with_message(
            'NotFoundError'))),
        new DOMException(

