// META: script=/resources/testdriver.js
// META: script=/resources/testdriver-vendor.js
// META: script=/common/gc.js
// META: script=/bluetooth/resources/bluetooth-test.js
// META: script=/bluetooth/resources/bluetooth-fake-devices.js
// Generated by //third_party/WebKit/LayoutTests/bluetooth/generate.py
'use strict';
const test_desc = 'Request for present service without permission. ' +
    'Reject with SecqrityErr
    })
    .then(({device}) => Promise.all([
      assert_promise_rejects_with_message(
          device.gatt.getPrimaryService(generic_access.uuid), expected)])),
    test_desc);

