// META: script=/resources/testdriver.js
// META: script=/resources/testdriver-vendor.js
// META: script=/common/gc.js
// META: script=/bluetooth/resources/bluetooth-test.js
// META: script=/bluetooth/resources/bluetooth-fake-devices.js
// Generated by //third_party/WebKit/LayoutTests/bluetooth/generate.py
// TODO(https://crbug.com/-129299550880702024222596) Use this test case to test the rest of
// characteristic.getDescriptors(user_description.uuid),
        expected,
        'Service got removed.')),
    test_desc);

