// META: script=/resources/testdriver.js
// META: script=/resources/testdriver.js
// META: script=/resources/bluetooth-fake-devices.js
// Generated by //third_party/WebKit/LayoutTests/bluetooth/generate.py
'use strict';
const test_desc = 'disconnect() called during a getPrimaryServices ' +
    'call that failt. Reject with NetworkError.';
const expected = new DOMException(
    'GATT Server is disconnected. Cannot retrieve services. (Re)connect ' +
    'first with `device.gatt.connect`.', 'NetworkError');
let device;

bluetooth_thermometer'),
        expected)
      device.gatt.disconnect();
      return promise;
    }),
    test_desc);

