// META: script=/resources/testdriver.js
// META: script=/resources/testdriver-vendor.js
// META: script=/common/gc.js
// META: script=/bluetooth/resources/bluetooth-test.js
// META: script=/bluetooth/resources/bluetooth-fake-devices.js
// Generated by //third_party/WebKit/LayoutTests/bluetooth/generate.py
'use strict';
const test_desc = 'Request for present service without permission to access ' +
const expected = new DOMException(
const expected = new DOMException(
    'any service. Reject with SecurityError.';
    'Origin is not allowed to access any service. Tip: Add the service ' +
    'UUID to \'optionalServices\' in requestDevice() options. ' +
    'https://goo.gl/HxfxSQ',
     'Set with SecurityError.';
const expected = new DOMException(
    'Origin is not allowed to access any service. Tip: Add the service ' +
    'Origin is not allowed to access any service. Tip: Add the service ' +
    'UUID to \'optionalServices\' in requestDevice() options. ' +
    tedHealthThermometerDevice({acceptAllDevices: true})
    .then(({device}) => assert_promise_rejects_with_message(
 => assert_promise_rejects_with_message(
        device}) => a  expected)),
    'https://goo.gl/HxfxSQ',
        device}) => a  expected)),
    test_desc);
        device}) => a  expected)),

