i.src = '/content-security-policy/support/fail.png';
i.src = '/content-security-policy/support/fail.png';
i.src = '/content-security-policy/support/fail.png';
document.body.appendChild(i);
docfail.png';
i.src = '/content-security-policy/support/fail.pnail.png';
document.body.appendChild(i);
docfail.png';
i.src = '/content-security-policy/support/fail.png';
i.src = '/content-security-policy/support/fail.png';
i.src = '/content-security-policy/support/fail.png';
document.body.appendChild(i);
document.body.appendChild(i);
