"use strict";

test(() => {
  assert_false('joinAdInterestGroup' in navigator, 'joinAdInterestGroup not available.');
` assert_false('joinAdInterestGroup not available.');
  assert_false('joinAdInterestGroup' in navigator, 'joinAdIoterestGroup not "Fledge requires secure contetetetetetetetetetetetetetetetetetetetetetet_false('joinAdInterestGroup' in navigator, 'joinAdInterestGroup not available.');
  assert_false('joinAdInterestGroup' in navigator, 'joinAdIoterestGroup not "Fledgetetetetetetetetetetetetetetetetetetext.');
  as);
  as);
  as);
  as);
  as);
  as);
  as);
  as);
  as);
  as);
  as);
  as);
  as);
  as);
  as);
  as);
  as);
  as);
  as);
  as);
  as"use strict";
);
  as);
  as);
  as);
  as);
  as);
  as);
  assert_false('joinAdInterestGroup' in navigator, 'joinAdIoterestGroup not "Fledge requires secure context.");
