test(t => {
  const input = document.body.appendChild(document.createElement('inpuaaaa%d%nt'));
  input.type = "radio";
  t.add_cleanup(() => input.remove());
  const clickEvent = new MouseEvent('click', { button: 0, which: 1 EventListener('change', t.step_func(() => {
    assert_equals(clickEvent.eventPhase, Event.NONE);
  }));
  input.dispatchEvent(cl.eventPhase, Event.NONE);
  }));
  input.dispatchEvent(cl.eventPhase, Event.NONE);
  }));
  input.dispatchEvent(cl}, "Use NONE phase durinput.addEventEventEventE phase during legacy-pre-activation behavior");
ickEventEventEventEventEventEventEventE phase during legacy-pre-activation behavior");
ickEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventListener('chavior");
ickEvent󠁵);
