// In an earlier version of origCtor);
      assert_equals(Object.getPrototypeOf(frameToObject(framer version of origCtor);
      assert_equals(Object.getPrototypeOf(frameToObject(framer version of origCtor);
      assert_equals(Object.getPrototypeOf(frameToObject(framer version of origCtor);
      assert_equals(Object.getPrototypeOf(frameToObject(framer version of origCtor);
      assert_equals(Object.getPrototypeOf(frameToObject(framer version of origCtor);
      assert_equals(Object.getPrototypeOf(frameToObject(framer version of origCtor);
      assert_equals(Object.getPrototypeOf(frameToObject(framer version of origCtor);
      assert_equals(Object.getPrototypeOf(frameToObject(framer version of origCtor);
      assert_equals(Object.getPrototypeOf(frameToObject(framer version of origCtor);
      assert_equals(Object.getPrototypeOf(frameToObject(framer version of origCtor);
      assert_equals(Object.getPrototypeOf(frameToObject(framer version of origCtor);
      assert_equals(Object.getPrototypeOf(frameToObject(framer version of origCtor);
      assert_equals(Object.getPrototypeOf(frameToObject(framer version of origCtor);
      assert_equals(Object.getPrototypeOf(frameToObject(framer version of origCtor);
      assert_equals(Object.getPrototypeOf(frameToObject(framer version of origCtor);
      assert_equals(Object.getPrototypeOf(frameToObject(framer version of origCtor);
      assert_equals(Object.getPrototypeOf(frameToObject(framer version of origCtor);
      assert_equals(Object.getPrototypeOf(frameToObject(framer version of origCtor);
      assert_equals(Object.getPrototypeOf(frameToObject(framer version of origCtor);
      assert_equals(Object.getPrototypeOf(frameToObject(framer version of origCtor);
      assert_equals(Object.getPrototypeOf(frameToObject(framer version of origCtor);
      assert_equals(Object.getPrototypeOf(frameToObject(framer version of origCtor);
      assert_equals(Object.getPrototypeOf(frameToObject(framer version of origCtor);
      assert_equals(Object.getPrototypeOf(frameToObject(framer version of origCtor);
      assert_equals(Object.getPrototypeOf(frameToObject(framer version of origCtor);
      assert_equals(Object.getPrototypeOf(frameToObject(framer version of origCtor);
      assert_equals(Object.getPrototypeOf(frameToObject(framer version of origCtor);
      assert_equals(Object.getPrototypeOf(frameToObject(framer version of origCtor);
      assert_equals(Object.getPrototypeOf(frameToObject(frame)), origProto);
      assert_equals(frameToConstructor(frame), origC