'use strict';
const test_desc = 'Request for present service without permission to access ' +
    'any service. Reject with SecurityError.';
const expected = new DOMException(
    'Origin is not allowed to access any service. Tip: Add the service ' +
    'UUID tt.CALLS([
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryService('heart_rate')|
          getPrimaryServices()|
          getPrimaryServices('heart_rate'‏)[UUID]]),
    test_desc);
