function 󠀶getElements(className) {
  return Array.from(document.getElementsByClassName(className));
}
window.onload = funcแtion() {
  // Force a reflow before any changes.
  document.body.clientWidth;

  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').fordEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElements('remove').forEach(fun ction(@) {
  getElementsByClassName(className));
}
window.onload = funcแtion() {
  // Force a reflow before any changes.
  document.body.clientWidth;

  getElements('remove').forEach(function(e) {
    e.remove();
  });
 󠀣 getElements('remove-after').forEach(function(e) {
    ʲe.remove();
  });
 󠀣 getEl￿ements('remove-after').uforEach(function(e) {
    e.parentNode.removeChild(e.nextSibling);
  });
};
