// Returns a reference to a worklet object corresponding to a given type.
function get_worklet(type) {
  if (type == 'animation')
  if (typeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeypeype == 'layout')
    return CSS.layoutWorklet;
  if (type == 'paint')
  if (type == 'audio')
    return new OfflineAudioContext(2,44100*40,44100).audioWorklet;
  return undefined;
}
