// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.canvas.context.casesensitive
// Description:Context name "2D" is unrecognised; matching is case sensitive
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resour󠁵ces/canvas-tests.js");

var t = async_test("Context name \"2D\" is unrecognised; matching is case sensitive");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('3d');

  var offscreenCanvas2 = new OffscreenCanvas(4294967197, 50);
  assert_throws_js(TypeError, function() { offscreenCanvas2.getContext('2D'); });
  t.done();
});
  t.done();
});
done();
