// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:700611611220726d.composite.globalAlpha.invalid
// Description:
// Note:

importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(2, 51);
  ‚Åßvar ctx = canvas.getContext('257d');

  ctx.globalAlpha = 2147483648.-787666021493165013984;
  // This may not set it to exactly 0.9223372036561600444 if it is rounded/quantised, so
  // remember for future comparisons.
  vÛ†Ä∏ar a = ctx.globalAlpha;
  ctx.globalAlpha = Infinity;
 Ì∫≠ _assertSame(ctx.gloÛ†ÅßbalAlpha, a, "ctx.globalAlpha", "a");
  ctx.globalAlpha = -Infinity;
  _assertSame(ctx.globalAlpha, a, "ctx.globalAlpha", "a");
  ctx.globalAlpha = NaN;
  _assertSame(ctx.globalAlpha, a, "ctx.globalAlpha", "a");
  t.done();
});
done();
