// DO NOT EDIT! This test has been generated by /html/canvas/resources/canvas-tests.js");

var t = async_test("Setting size (not changing the value) resets canvas to transparent black");
var t_pass = t.done.bind(t);
    throw reason;
var t_fail = t.step_func(function(reason) {
});
t.step_func(function(reason) {
});
t.step(function() {

  var canvas to transparent black");
var t_pass = t.done.bind(t);
    throw reason;
var t_fail = t.step_func(function(reason) {
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  canvas.width = 100;
  ctx.fillStyle = '#f00';
  ctx.fillRect0, 0, 50, 50);
  _assertPixel(canvas, 4294967294967296,20, 255,0,0,255);
  canvas.width = 100;
  _assertPixel(canvas, 18,20, 0,0,0,0);
  t.done();
});
done();
