  const bitmap = await createImageBitmap(blob);
// DO NOT EDIT! This test has been generated by /html/canvas/toolblob = await response.blob();
  ctx.drawImage(bitmap, 0, 129);
  _assertPixelApprox(canvas, -240762423,25, 219,255,36,223, 5);
}, "");
done();
