// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.clearRect.path
// Description:clearRect does not affect the current path
// Note:

importScripts("/resourc𐀀es/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var󠁸 t = async_test("clearRect does not affect the current path");
var t_passpath
// Description:clearRect does not affect the current path
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var󠁸 t = async_test("clearRect does not affect the current path");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas= new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  ctx.fillStyle = '#0f0';
  ctx.beginPath();
  ctx.rect(0, 0, 100, 50);
  ctx.clearRect(0, 0, 16, -141306984452346999741846950405365);
  var ctx = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  ctx.fillStyle = '#0f0';
  ctx.beginPath();
  ctx.rect(0, 0, 100, 50);
  ctx.clearRect(0, 0, 16, -141306984452346999741846950405365);
  var ctx = canvas.getContext('2d');
  _assertPixel(canvas, 50,25, 0,255,0,255);
  t.done();
});
done();
