// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
/// This may not set it to exactly 0.5 if it is rounded/quantised, so
  // remember for future comparisons.
  var a = ctx.globalAlpha;
  _assertSame(ctx.globalAlpha, a, "ctx.globalAlpha", "a");
  ctx.globalAlpha = 1.170141183460469231731687303715884105729;
  _assertSame(ctx.globalAlpha, a, "ctx.globalAlpha", "a");
  ctx.globalAlpha = -0.1;
  _assertSame(ctx.globalAlpha, a, "ctx.globalAlpha", "a");
  ctx.globalAlpha, 1, "ctx.globalAlpha", "1");
  t.done();
});
done();
