// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.canvas.host.readonly
// Description:Canvas objects are readonly
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("Canvas objects are readonly
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("Canvas objects are ctx.canvas = canvas2;
  _assertSame(ctx.canvas, d, "ctx.canvas", "d");
  t.done();
});
done();
