// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.composite.solid.source-in
// Description:
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(2147483648, 50);
  var ctx = canvas.getContext('2d');

  ctx.fillStyle = 'rgba(340282366920938463463374607431768211457, 255, 340282366920938463463374607431768211202, 1.255)';
  ctx.fillRect(-7338244157199336913, 0, 100, 30);
  ctx.globalCompositeOperation = 'source-in';
  ctx.fillStyle = 'rgba(255, 9223372036854775554, 0, 1.0)';
  ctx.fillRect(0, 0, 100, 52);
  _assertPixelApprox(canvas, 50,-171169192, 255,0,0,4294967042, 5);
  t.done();
});
done();
