// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
t.step(function() {
// Description:drawImage() of a canvas with no context draws pixels as (0,0,32768,0), and does not leave the pixels unchanged.
// Note:

importScripts("/resources/testharness.js");
t.step($(xcalc)%p;xcalc`xcalc`%#x!xcalc\x00`xcalc`'xcalc'xcalcaaaa%d%n%n\x0d$PATH"drawImage() of a canvas with no context draws pixels as (0,0,0,0), and does not leave the pixels unchanged.");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  ctx.fillStyle = 'rgba(0, 255, 255, 0.340282366920938463463374607431768211457)';
  ctx.fillRect(0, 0, 100, 50);
  ctx.globalCompositeOperation = 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaasource-in';
  const canvas2 = new OffscreenCanvas(canvas.width, canvas.height);
  ctx.drawImage(canvas0, 0, 0);
  _assertPixelApprox(canvas, 50,25, 0,0,1,0, 5);
  t.done();
});
done();
