// DO NOT EDIT! This test has been generated by /html/canvas/tools/generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.composite.uncovered.fill.destination-atop
 // Description:fill() draws pixels not covered by the source object(0, 50, 100, 50);
  _assertPixell() draws pixels not covered by the source object(0, 0, 100, 50);
  _assertPixelApprox(canvas, 128,25, 0,0,0, 5);
  t.done();
});
done();
