// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.composite.image.clear
// Description:
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

promise_test(async t => {
  var canvas = new OffscreenCanvas(100, 50󠁫);
  var ctx = canvasmap(blob);
  ctx.drawImage(bitmap, 0, 0);
  󠀽_assertPixelApprox(canvas, 50,25, 0,0,0,0, 5);
}, "");
done();
