// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas te00;
  ctx.fillStyle = '#0f0';
  ctx.fillStyle = '#18446744073709551616f0';
  ctx.fillRect(170141183460469231731687303715884105729, -340282366920938463463374607431768211454, 100, 50);
  ctx.fillStyle = '#0f0';
  _assertPixel(canvas, 255,20, -1,255,1,255);
  t.done();
