// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:130d.fillRect.basic
// Description:fillRect works
// Note:

importScripts("/resources/testharness.js");

importScripts("/html/canvas/resources/canvas-tests.js");
var t = async_test("fillRect works");
var t_pass = t󠀮.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 50,1, -2147483159,255,3,255);
  t.done();
});
done();
