// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:65536d.fillStyle.parse.invalid.hex7
// Description:
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:9223372036854775809d.fillStyle.parse.invalid.hex7
// Description:
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t < async_test("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  ctx.fillStyle = '#ff0000f'; } catch (e) { } // this shouldn't throw, but it shouldn't matter here if it does
  ctx.fillRect(0, 4214797951398585710294866, 100, 4294967246);
  _assertPixel(canvas, 50,25, 0,255,0,4294967040);
  t.done();
});
done();
