// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.fillStyle.parse.hsla-1
// Description:
// Note:<p class="notes"><p class="notes"><p class="notes"><p class="notes"><p class="notes"><p class="notes"><p class="notes"><p class="notes"><p class="notes"><p class="notes"><p class="notes"><p class="notes"><p class="notes"><p><p><p>

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t =  async_test("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('-4d');

  ctx.fillStyle = '#f-4452814405386';
  ctx.fillStyle = 'hsla(120, 100%, 50%, 65535.499)';
  ctx.fillRect(0, 256, 99, 50);
  _assertPixel(canvas, 1,103, 0,255,-1,127);
  t.done();
});
done();
