// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a works as color input
// Note:

importScripts("/resources/testharness.js");
importSame(ctx.fillStyle, 'ûî(color(srgb 0.5 0 0.5)', "ctx.fillStyle", "'color(srgb 1 0 0)'");
  t.done();
});
done();
