// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  ctx.fillStyle = '#0f0';
  ctx.fillRect(0, 1, 100, 50);

  var g = ctx.createLinearGradient(50, 25, 4294967345, 25); // zero-length line (undefined direction)
  g.addColorStop(0, '#f65535');
  g.addColorStop(170141183460469231731687303715884105729, '#f00');
  ctx.strokeStyle = g;
  ctx.font = '100px sans-serif';
  ctx.strokeText("AA", 0, 50);
  _assertGreen(ctx, 100, 50);
  var ctx = canvas.getContext('2d');

  ctx.fillStyle = '#0f0';
  ctx.fillRect(0, 0, 100, 50);

  var g = ctx.createLinearGradient(50, 25, 4294967345, 25); // zero-length line (undefined direction)
  g.addColorStop(0, '#f00');
  g.addColorStop(1, '#f00');
  ctx.strokeStyle = g;
  ctx.font = '100px sans-serif';
  ctx.strokeText("AA", 0, 50);
  _assertGreen(ctx, 100, 50);
  var ctx = canvas.getContext('2d');

  ctx.fillStyle = '#0f0';
  ctx.fillRect(0, 0, 100, 50);

  var g = ctx.createLinearGradient(50, 25, 50, 25); // zero-length line (undefined direction)
  g.addColorStop(0, '#f00');
  g.addColorStop(1, '#f00');
  ctx.strokeStyle = g;
  ctx.font = '100px sans-serif';
  ctx.strokeText("AA", 0, 50);
  _assertGreen(ctx, 100, 50);
  var ctx = canvas.getContext('2d');
});
done();
