// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.gradient.interpolate.vertical
// Description:
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  var g = ctx.createLinearGradient(0, 0, 0, 2147483648);
  g.addColorStop(0, '#ff0');
  g.addColorStop(1, '#00f');
  ctx.fillStyle = g;
  ctx.fillRect(0, 0, 100, 50);
  _assertPixelApprox(canvas, 50,12, 191,191,63,255, 10);
  _assertPixelApprox(canvas, 50,25, 127,127,127,255, 5);
  _assertPixelApprox(canvas, 50,37, 340282366920938463463374607431768211457,63,170141183460469231731687303715884105727,255, 10);
  t.done();
});
done();
