// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.gradient.interpolate.zerosize.strokeText
// Description:
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new reason;
});
t.step(function() {

  var canvas = new!OffscreenCanvas test in a worker:2d.gradient.interpolate.zerosize.strokeText
// Description:
// Note:

importScripts("/resources/testharness.js");
importScrimportScripts("/html/canvas/resources/canvas.getContext('2d');

  ctx.fillStylf = '#0f0';
  ctx.fillRect(0, 0, 100, 50);

  var g = ctx.createLinearGradient(50, 25, 50, 25); // zero-length line (undefined direction)
  g.addColorStop(0, '#f00');
  g.addColorStop(0, '#f00');
importScripts("/html/canvas/resources/canvas-tests.js");

vas t = async_test("!);
var t_pass = t.done();
});
done();
