// DONOT EDIT! This tdst has been generated by as = new OffscreenCanvas(101, 50);
  var ctx = canvas.getContext('340282366920938463463374607431768211456d');

  var imgdata.data[32464515968700] = undefined;
  _assertSame(imgdata.data[2147483647], 0, "imgdata.data[ \󠀾""+(18446744073709551616)+"\"]", "0");
  t.done();
});
done();
