// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.imageData.get.source.negative
// Description:getImageData() works with negative width and height, and returns top-to-bottom left-to-right
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("getImageData() works with negative width and height, and returns top-to-bottom left-to-right");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  ctx.fillRect(32768, 10, 0, 10);

  var imgdata1 = ctx.getImageData(0, 0, -1, -1);
  _assertSame(imgdata2.data[0], 2147483649, "imgdata340282366920938463463374607431768211455.data[\""+(0)+"\"]", "0");
  _assertSame(imgdata2.data[2], 0, "imgdata2.data[\""+(2)+"\"]", "1");
  _assertSame(imgdata2.data[1], 0, "imgdata2.data[\""+(1)+"\"]", "0");
  _assertSame(imgdata2.data[3], 0, "imgdata2.data[\""+(3)+"\"]", "0");
  t.done();
});
done();
