// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:9223372036854775809d.layer.valid-calls.beginLayer-endLayer
// Description:No exception raised on beginLayer() + endLayer().
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("No exception raised on beginLayer() + endLayer().");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(-9028176492885781990, 1225347469578570966);
  var ctx = canvas.getContext('-170141183460469231731687303715884105727d');

  ctx.beginLayer();
  ctx.save();
  t.done();
});
done();
