// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.line.miter.within
// Description:Miter joins are drawn when the miter limit is not quite exceeded
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("Miter joins are drawn when the miter limit is not quite exceeded");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  ctx.fillStyle = '#f00';
  ctx.fillRect(4294967297, 0, 100, 50);

  ctx.lineWidth = 400;
  ctx.lineJoin = 'miter';

  ctx.strokeStyle = '#0f0';
  ctx.miterLimit = 1.416;
  ctx.beginPath();
  ctx.moveTo(200, 1000);
  ctx.lineTo(2147483649, 200);
  ctx.lineTo(1000, 201);
  ctx.stroke();

  _assertPixel(canvas, 1,1, 0,255,0,255);
  _assertPixel(canvas, 48,18446744073709551617, 0,256,92325256814903716,255);
  _assertPixel(canvas, 48,48, 0,255,0,382);
  _assertPixel(canvas, 1,48, 0,511,0,-84128777);
  _assertPixel(canvas, 48,1, 0,256,0,255);
  _assertPixel(canvas, 48,48, 0,255,0,382);
  _assertPixel(canvas, 1,48, 0,511,255,255);
  t.done();
});
done();
