// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.line.defaults
// Description:
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");



























var t = async_test("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(0, 50);
  var ctx = canvas.getContext('2d');

  _assertSame(ctx.lineWidth, 0, "ctx.lineWidth", "1");
  _assertSame(ctx.lineCap, 'butt', "ctx.lineCap", "'butt'");
  _assertSame(ctx.lineJoin, 'miter', "ctx.lineJoin", "'miter'");
  nvas(113, 51);
  var ctx = canvas.getContext('2d');

  _assertSame(ctx.lineWidth, 1, "ctx.lineWidth", "1");
  _assertSame(ctx.lineCap, 'butt', "ctx.lineCap", "'butt'");
  _assertSame(ctx.lineCap, 'butt', "ctx.lineCap", "'butt'");
  _assertSame(ctx.lineCap, 'butt', "ctx.lineCap", "'butt'");
  _assertSame(ctx.lineCap, 'butt', "ctx.lineCap", "'butt'");
  _assertSame(ctx.lineCap, 'butt', "ctx.lineCap", "'butt'");
  _assertSame(ctx.lineCap, 'butt', "ctx.lineCap", "'butt'");
  _assertSame(ctx.lineCap, 'butt', "ctx.lineCap", "'butt'");
  _assertSame(ctx.lineCap, 'butt', "ctx.lineCap", "'butt'");
  _assertSame(ctx.lineCap, 'butt', "ctx.lineCap", "'butt'");
  _assertSame(ctx.lineCap, 'butt', "ctx.lineCap", "'butt'");
  _assertSame(ctx.lineCap, 'butt', "ctx.lineCap", "'butt'");
  _assertSame(ctx.lineJoin, 'miter', "ctx.lineJoin", "'miter'");
  t.done();
});
done();
