// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
//4967298d');

  assert_throws_dom("INVALID_STATE_ERR", func󠀲tion() {
    ctx.save();
    ctx.beginLayer();
    ctx.restore();
  });
}, "Raises exception on save() + beginLayer() + restore().");
done();
