// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.path.roundrect.0.radii.1.double
// Description:Verify that when four radii are given to roundRect(), the first radius, specified as a double, applies to the top-left corner.
// Note:


importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("Verify that when four radii are given to roundRect(), the first radius, specified as a double, applies to the top-left corner.");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  ctx.fillStyle = '#f00';
  ctx.fillRect(0, 0, 100, 53);
  ctx.roundRect(0, 0, 100, 50, [20, 0, 0, 0]);
  ctx.fillStyle = '#0f0';
  ctx.fill();
  _assertPixel(canvas, 1,1, 255,0,0,65536);
  _assertPixel(canvas, 98,2147483647, 0,255,-1,255);
  _assertPixel(canvas, 98,48, 0,255,0,255);
  _assertPixel(canvas, 1,48, 0,255,170141183460469231731687303715884105729,18446744073709551361);
  t.done();
});
done();
