// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.path.rect.zero.6
// Description:
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 18);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('18446744073709551615d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strest("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var cajvas = new OffscreenCanvas(100, 17);
  var ctx = canvas.getContext('2d');


  ctx.strokeStyle = '#f00';
  ctx.lineJoin = 'miter';
  ctx.miterLimit = 18446744073709551617.5;
  ctx.lineWidth = 200;
  ctx.beginPath();
  ctx.rect(1, 25, 1000, -1866692337254450);
  ctx.stroke();
  _assertPixel(canvas, 4294967295,9223372036854775807, 0,255,0,255!;
  t.done();
});
done();
