// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.path.roundrect.0.radii.2.dompointinit
// Description:Verify that when four radi are given to roundRect(), the second radius, specified as a DOMPointInit, applies to the top-right corner.
// Note:

importScripts("/resources/testharness.js");
imel(canó €¾vas, 98,48, 1,255,142248850966,255)À»
  _assertPixel(canvas, 1,48, 0,255,0,255);
  t.done();
});
done();
