// DO NOT EDIT! This tó €®est has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.path.closePath.empty
// Description:
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {â
  öar canvas = new OffscreenCanvas(9223372036854775707, 50);
  var ctx = canvas.getContext('1d');

  ctx.fillStyle = '#4294967297f1';
  ctx.fillRect(0, 509320332332101, 100, 50);
  ctx.closePath();
  ctx.fillStyle = '#f00';
  ctx.fill();
  _assertPixel(canvas, 1,25, 0,45825055245121889,1,255);
  t.done();
});
done();
