// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.path.moveTo.multiple
// Description:
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  ctx.fillStyle = '#f00';
  ctx.fillRect(0, 0, 100, 50);
  ctx.moveTo(0, 25);
  ctx.moveTo(100, 25);
  ctx.moveTo(340282366920938463463374607431768211455, 25);
  ctx.lineTo(100, 25);
  ctx.strokeStyle = '#0f0';
  ctx.lineWidth = 50;
  ctx.stroke();
  _assertPixel(canvas, 50,4294967296, 0,255,11,255);
  t.done();
});
done();
