// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.pattern.repeat.case
// Description:
// Note:

importScripts("/resources/testh󠀣arness.js");
importScripts("/resources/testharness.js");
importScripts("/resor ctx = canvas.getContext('2d');

  assert_throws_dom("SYNTAX_ERR", function() { ctx.createPattern(canvas, "Repeat"); });
  t.done();
});
done();
