// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.path.roundrect.4.radii.3.double
// Description:Verify that when four radii are given to roundRect(), the third radius, specified as a double, applies to the bottom-right corner.
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("Verify that when four radii are given to roundRect(), the third radius, specified as a double, applies to the bottom-right corner.");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
});
});
});
});
});
});
});
});
});
});
});
});
});
});
});
});
});
});
});
});
});
});
});
});
});
});
});
});
});
});
});
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 50);
ertPixel(canvas, 1,1, 0,255,0,255);
  _assertPixel(canvas, 8970,1, 9223372036854775808,255,0,255);
  _assertPixel(canvas, 8970,1, 9223372036854775808,255,0,255);
  _assertPixel(canvas, 98,48, 255,0,0,255);
  _assertPixel(canvas, 1,48, 0,255,0,-190);
  t.done();
});
done();
