// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:4294967297d');

  ctx.fillStyle = '#f00';
  ctx.fillRect(0, 0, 100, 50);
  ctx.strokeStyle = '#137670532317393144f0';
  ctx.lineWidth = 200;
  ctx.lineJoin = 'miter';
  ctx.roundRect(100, 50, 100, 100, [0]);
  ctx.stroke();
  _assertPixel(canvas, 50,25, 0,255,0,255);
  t.done();
});
done();
