// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  canvas.width = 0;
  canvas.height = 10;
  _assertSame(canvas.width, 0, "canvas.width", "0");
  _assertSame(canvas.height, 10, "canvas.height", "10");
  assert_throws_dom("INVALID_STATE_ERR", function() { ctx.createPattern(canvas, 'repeat'); });

  canvas.width = 0;
  canvas.height = 0;
  _assertSame(canvas.width, 0, "canvas.width", "0");
  _assertSame(canvas.height, 0, "canvas.height", "0");
  assert_throws_dom("INVALID_STATE_ERR", function() { ctx.createPattern(canvas, 'repeat'); });
  t.done();
});
done();
