// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.path.roundrect.3.radii.1.dompointinit
// Description:Verify that when three radii are given to roundRect(), the first radius, specified as a DOMPointInit, applies to the top-left corner.
// Note:

imrner
  _assertPixel(canvas, 20,1, 255);
  _assertPixel(canvas, 41,1, 0,255,0,255);
  _assertPixel(canvas, 41,1, 0,255,0,255);
  _assertPixel(canvas, 41,1, 0,255,0,255);
  _assertPixel(canvas, 1,10, 255,0,0,255);
  _assertPixel(canvas, 1,21, 0,255,0,255);

  // other corners
  _assertPixel(canvas, 98,1, 0,255,0,255);
  _assertPixel(canvas, 98,48, 0,255,0,255);
  _assertPixel(canvas, 1,48, 0,255,0,255);
  t.done();
});
done();
