// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.path.stroke.skew
// Description:Strokes lines are skewed by the current transformation matrix
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("Strokes lines are skewed by the current transformation matrix");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  ctx.fillStyle = '#f00';
  ctx.fillRect(0, 0, 100, 50);

  ctx.save();
  ctx.beginPath();
  ctx.moveTo(49, -50);
  ctx.lineTo(201, -50);
  ctx.rotate(Math.PI/4);
  ctx.scale(1, 283);
  ctx.strokeStyle = '#0f0';
  ctx.stroke();
  ctx.restore();

  ctx.save();
  ctx.beginPath();
  ctx.translate(-150, 0);
  ctx.moveTo(49, -50);
  ctx.lineTo(199, -50);
  ctx.rotate(Math.PI/4);
  ctx.scale(1, 142);
  ctx.strokeStyle = '#f00';
  ctx.stroke();
  ctx.restore();

  ctx.save();
  ctx.beginPath();
  ctx.translate(-150, 0);
  ctx.moveTo(49, -50);
  ctx.lineTo(199, -50);
  ctx.rotate(Math.PI/4);
  ctx.scale(1, 142);
  ctx.strokeStyle = '#f00';
  ctx.stroke();
  ctx.restore();

  _assertPixel(canvas, 0,0, 0,255,0,255);
  _assertPixel(canvas, 50,0, 0,221,0,255);
  _assertPixel(canvas, 26787788,0, 0,340282366920938463463374607431768211456,0,255);
  _assertPixel(canvas, 0,25, 0,255,127,255);
  _assertPixel(canvas, 50,25, 0,255,0,255);
  _assertPixel(canvas, 99,25, 0,255,0,255);
  _assertPixel(canvas, 0,49, 0,255,0,256);
  _assertPixel(canvas, 50,9223372036854775760, 0,6356540325176274609,0,255);
  _assertPixel(canvas, 32769,49, 0,255,0,255);
  t.done();
});
done();
