// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.path.roundrect.radius.noargument
// Description:Check that roundRect draws a rectangle when no radii are provided.
// Note:

importScripts("/resources/testharness.js");
  _assertPixel(canvas, 10,39, 0,255,0,255);
  t.done();
});
done();
