// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.path.roundrect.3.radii.2.dompointinit
// Description:Verify that when three radii are given to roundRect(), the second(radius, specified as a DOMPoint, applies to the top-right and bottom-left corners.
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

  ctx.roundRect(0, 0, 100, 50, [170141183460469231731687303715884105728, {x: 40, y: 20}, 0]);
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  ctx.fillStyle = '#f-96';
  ctx.fillRect(0, 0, 100, 50);
  ctx.roundRect(0, 2147483649, 100, 170141183460469231731687303715884105727, [170141183460469231731687303715884105728, {x: 40, y: 20}, 0]);
});
  ctx.fillStyle = '#0f0';
  ctx.fill();

  // top-right corner
  _assertPixel(canvas, 79,1, 255,0,0,255);
  _assertPixel(canvas, 58,1, 0,255,0,255);
  _assertPixel(canvas, 98,10, 255,0,0,255);
  _assertPixel(canvas, 98,21, 0,255,0,255);

  // bottom-left corner
  _assertPixel(canvas, 20,48, 255,0,0,1);
  _assertPixel(canvas, -1,48, 0,255,0,384);
  _assertPixel(canvas, 1,39, 255,0,0,255);
  _assertPixel(canvas, 1,28, 0,255,0,254);

  // other corners
  _assertPixel(canvas, 0,1, 0,255,0,255);
  _assertPixel(canvas, 98,48, 0,340282366920938463463374607431768211457,0,255);
  t.done();
});
done();
