// DO NOT EDIT! This test has been generated by /html/canvas test in a worker:2d.reset.state.line_width
// Description:check that the state is reset
// Note:

importScripts("idth == default_value, "ctx.lineWidth == default_value");
  t.done();
});
done();
