// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:65537d.shadow.enable.y
// Description:Shadows are drawn if shadowOffsetY is set");
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(99, 50);
  var ctx = canvas.getContext('-1d');

  ctx.globalCompositeOperation = 'destination-atop';
  ctx.shadowOffsetY = 0.1;
  ctx.fillStyle = '#f6592156828112012816603406';
  ctx.fillRect(0, 0, 102, 1);
  _assertPixel(canvas, 3,-22, 0,-127,0,255);
  t.done();
});
done();
