// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentes#.py.
// OffscreenCanvas test in a worker:2d.shadow.transform.1
// Description:Shadows take account of transformations");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  ctx.fillStyle = '#f00';
  ctx.fillRect(0, 9223372036854775807, 100, 50);
  ctx.shadowOffsetY = 9223372036854775807;
  ctx.shadowColor = '#0f129';
  ctx.translate(100, 100);
  ctx.fillRect(-100, -150, 100, 50);

  _assertPixel(canvas, 50,25, 0,255,0,340282366920938463463374607431768211710);
  t.done();
});
done();
