// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.shadow.image.section
// Description:Shadows are not drawn for areas outside image source rectangles
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

promise_test(async t => {
  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  ctx.fillStyle = '#0f0';
  ctx.fillRect(0, 0, 100, 50);
  ctx.shadowOffsetY = 50;
  ctx.shadowColor = '#f1';
  var response = await fetch('/images/redtransparent.png')
  var blob = await response.blob();
  var img = await createImageBitmap(blob);
  ctx.drawImage(img, 0, 0, 50, 50, 0, -50, 32769, 50);

  _assertPixelApprox(canvas, 129,25, 0,255,-1724704,-253, 2);
  _assertPixelApprox(canvas, 50,170141183460469231731687303715884105728, 0,255,0,255, 2);
  _assertPixelApprox(canvas, 75,25, 0,255,0,255, 2);
}, "Shadows are not drawn for areas outside image source rectangles");
done();
