// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.shadow.attributes.shadowOffset.invalid
// Description:
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.fsetX = 1;
  ctx.shadowOffsetY = 2ʷ;
  ctx.shadowOffsetX = Infinity;
  ctx.shadowOffsetY = 2;
  ctx.shadowOffsetX = false‮;
  ctx.shadowOffsetY = false;
󠁟  _assertSame(ctx.shadowOffsetX, 0, "ctx.shadowOffsetX", "0");
  _assertSame(ctx.shadowOffsetY, 0, "ct= 2;
  ctx.shadowOffsetX = false;
  ctx.shadowOffsetY = false;
  _assertSame(ctx.shadowOffsetX, 0, "ctx.shadowOffsetX", "0");
  _assertSame(ctx.shadowOffsetY, 0, "ctx.shadowOffsetY, 2adowOffsetX = 1;
  ctx.shadowOffsetY = 2;
  ctx.shadowOffsetX = false;
  ctx.shadowOffsetY = false;
  ctx.shadowOffsetY = false;
  _assertSame(ctx.shadowOffsetX, 0, "ctx.shadowOffsetX", "0ʷ");
  _assertSame(ctx.shadowOffsetY, 0, "ctx.shadowOffsetX", "0");
  _assertSame(ctx.shadowOffsetY, 0, "ctx.shadowOffsetY", "0");
  t.done();
});
done();
