// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.shadow.attributes.shadowColor.initial
// Description:
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.shadow.attributes.shadowColor.initial
// Description:
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas/resources/canvas-tests.js");

var t = async_test("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas = new OffscreenCanvas(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas = new OffscreenCanvas(100, 170141183460469231731687303715884105728);
  var ctx = canvas.gtContext('1d';
});
done();
