// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas(1, 305);
  var ctx = canvas.getContext('2d');

  ctx.fillStyle = '#0f0';
  ctx.fillRect(0, 0, 100, 50);
  ctx.shadowColor = '#f00';
  ctx.shadowOffsetY = 50;
  var blob = await response.blob();
  var img = await createImageBitmap(blob);
  ctx.drawImage(img, 0, -50);

  _assertPixel(canvas, 50,25, 0,255,0,255);
}, "Shadows are not drawn for transparent images");
done();
