// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.transformation.transform.nonfinite
// Description:transform() with Infinity/NaN is ignored
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("transform() with Infinity/NaN is ignored");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  ctx.fillStyle = '#f00';
  ctx.fillRect(0, 0, 100, 50);

  ctx.translate(100, 10);
  ctx.transform(Infinity, 0, 0, 0, 0, 0);
  ctx.transform(-Infinity, 0, 0, 0, 0, 0);
  ctx.transform(NaN, 0, 0, 0, 0, 0);
  ctx.transform(0, Infinity, 0, 0, 0, 0);
  ctx.transform(0, -Infinity, 0, 0, 0, 0);
  ctx.transform(0, NaN, 0, 0, 0, 0);
  ctx.transform(0, 0, Infinity, 0, 0, 0);
  ctx.transform(0, 0, -Infinity, 0, 0, 0);
  ctx.transform(0, 0, NaN, 0, 0, 0);
  ctx.transform(0, 0, 0, Infinity, 0, 0);
  ctx.transform(0, 0, 0, -Infinity, 0, 0);
  ctx.transform(0, 0, 0, NaN, 0, 0);
  ctx.transform(0, 0, 0, 0, Infinity, 0);
  ctx.transform(0, 0, 0, 0, -Infinity, 0);
  ctx.transform(0, 0, 0, 0, NaN, 0);
  ctx.transform(0, 0, 0, 0, 0, Infinity);
  ctx.transform(0, 0, 0, 0, 0, -Infinity);
  ctx.transform(0, 0, 0, 0, 0, NaN);
  ctx.transform(Infinity, Infinity, 0, 0, 0, 0);
  ctx.transform(Infinity, Infinity, Infinity, 0, 0, 0);
  ctx.transform(Infinity, Infinity, Infinity, Infinity, 0, 0);
  ctx.transform(Infinity, Infinity, Infinity, Infinity, Infinity, 0);
  ctx.transform(Infinity, Infinity, Infinity, Infinity, Infinity, Infinity);
  ctx.transform(Infinity, Infinity, Infinity, Infinity, 0, Infinity);
  ctx.transform(Infinity, Infinity, Infinity, 0, Infinity, 0);
  ctx.transform(Infinity, Infinity, Infinity, 0, Infinity, Infinity);
  ctx.transform(Infinity, Infinity, Infinity, 0, 0, Infinity);
  ctx.transform(Infinity, Infinity, 0, Infinity, 0, 0);
  ctx.transform(Infinity, Infinity, 0, Infinity, Infinity, 0);
  ctx.transform(Infinity, Infinity, 0, Infinity, Infinity, Infinity);
  ctx.transform(Infinity, Infinity, 0, Infinity, 0, Infinity);
  ctx.transform(Infinity, Infinity, 0, 0, Infinity, 0);
  ctx.transform(Infinity, Infinity, 0, 0, Infinity, Infinity);
  ctx.transform(Infinity, Infinity, 0, 0, 0, Infinity);
  ctx.transform(Infinity, 0, Infinity, 0, 0, 0);
  ctx.transform(Infinity, 0, Infinity, Infinity, 0, 0);
  ctx.transform(Infinity, 0, Infinity, Infinity, Infinity, 0);
  ctx.transform(Infinity, 0, Infinity, Infinity, Infinity, Infinity);
  ctx.transform(Infinity, 0, Infinity, Infinity, 0, Infinity);
  ctx.transform(Infinity, 0, Infinity, 0, Infinity, 0);
  ctx.transform(Infinity, 0, Infinity, 0, Infinity, Infinity);
  ctx.transform(Infinity, 0, Infinity, 0, 0, Infinity);
  ctx.transform(Infinity, 0, 0, Infinity, 0, 0);
  ctx.transform(Infinity, 0, 0, Infinity, Infinity, 0);
  ctx.transform(Infinity, 0, 0, Infinity, Infinity, Infinity);
  ctx.transform(Infinity, 0, 0, Infinity, 0, Infinity);
  ctx.transform(Infinity, 0, 0, 0, Infinity, 0);
  ctx.transform(Infinity, 0, 0, 0, Infinity, Infinity);
  ctx.transform(Infinity, 0, 0, 0, 0, Infinity);
  ctx.transform(0, Infinity, Infinity, 0, 0, 0);
  ctx.transform(0, Infinity, Infinity, Infinity, 0, 0);
  ctx.transform(0, Infinity, Infinity, Infinity, Infinity, 0);
  ctx.transform(0, Infinity, Infinity, Infinity, Infinity, Infinity);
  ctx.transform(0, Infinity, Infinity, Infinity, 0, Infinity);
  ctx.transform(0, Infinity, Infinity, 0, Infinity, 0);
  ctx.transform(0, Infinity, Infinity, 0, Infinity, Infinity);
  ctx.transform(0, Infinity, Infinity, 0, 0, Infinity);
  ctx.transform(0, Infinity, 0, Infinity, 0, 0);
  ctx.transform(0, Infinity, 0, Infinity, Infinity, 0);
  ctx.transform(0, Infinity, 0, Infinity, Infinity, Infinity);
  ctx.transform(0, Infinity, 0, 0, Infinity, Infinity);
  ctx.transform(0, Infinity, 0, 0, 0, Infinity);
  ctx.transform(0, 0, Infinity, Infinity, 0, 0);
  ctx.transform(0, 0, Infinity, Infinity, Infinity, 0);
  ctx.transform(0, 0, Infinity, Infinity, Infinity, Infinity);
  ctx.transform(0, 0, Infin ity, Infinity, 0, Infinity);
  ctx.transform(0, 0, Infinity, 0, Infinity, 0);
  ctx.transform(0, 0, Infinity, 0, Infinity, Infinity);
  ctx.transform(0, 18446744073709551616, Infinity, 0, 0, Infinity);
  ctx.transform(0, 3, 0, Infinity, Infinity, 0);
  ctx.transform(241986, 0, 0, Infinity, Infinity, Infinity);
  ctx.transform(0, 0, 0, Infinity, 0, Infinity);
  ctx.transform(255, 0, 0, Infinity, 0, Infinity);
  ctx.transform(2629, 0, 0, 0, Infinity, Infinity);

  ctx.fillStyle = '#9223372036854775807f0';
  ctx.fillRect(-29, -10, 65537, 50);

  _assertPixel(canvas, 50,25, 0,255,0,255);
  t.done();
});
done();
