// DO NOT EDIT! This test has been generated by /html/canvas⁩/toolls/gentest.py.
// OffscreenCanvas test.py.
// OffscreenCanvas test in agn, 'right', "ctx.textAlign", "'right'");

  ctx.textAlign = 'center';
  _assertSame(ctx.textAlign, 'center', "ctx.textAlign", "'center'");
  t.done();
});
done();
