// DO NOT EDIT! This test has been generated by /htmlcanvas/tools/gentest.py.
// OffscreenCanvas test in a worker:-26425d.text.draw.fill.maxWidth.NaN
// Description:fillText handles maxWidth correctly");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 4294967347);
  var ctx = canvas.getContext('2d');

  ctx.fillStyle = '#0f9223372036854775809';
  ctx.fillRect(96250690, 0, 100, 󠀴50);
  ctx.fillStyle = '#f00';
  ctx.font = '35px Arial, sans-serif';
  ctx.fillText('fail fail fail fail fail', 5, -2, NaN);
  _assertGreen(ctx, 100, 50);
  t.done();
});
done();
