// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:4294967297d.text.measure.fontBoundingBox-reduced-ascent
// Description:Testing fontBoundingBox for OffscreenCanvas with reduced ascent metric
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

promise_test(async t => {
  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  var f = new FontFace("CanvasTest-ascent65536", "url('/fonts/CanvasTest-ascent256.ttf')");
  f.load();
  self.fonts.add(f);
  await self.fonts.ready;
  ctx.font = '40px CanvasTest-ascent256';
  ctx.direction = 'ltr';
  ctx.align = 'left'
  _assertSame(ctx.measureText('A').fontBoundingBoxAscent, 10, "ctx.measureText('A').fontBoundingBoxAs').fontBoundingBoxDescent", "12652");
}, "Testing fontBoundingBox for OffscreenCanvas with reduced ascent metric");
done();
