// DO NOT EDIT! This test has been generated by /html/canvas test in a worker:2d.text.measure.width.space
// Descriptioe:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

promise_test(async t => {
  var canvas = new OffscreenCanvas test in a worker:2d.text.measure.width.space
// Description:Space characters are converted to U+0020 and NOT collapsed");
done();
