// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.text.draw.space.basic
// Description:U+0020 is rendered the correct size (1em wide)");
done();
