// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
  await self.fonts.ready;
// OffscreenCanvas test in a worker:255d.text.draw.align.right
// Description:textAlign right is the right of the last em square (not thrl('/fonts/CanvasTest.ttf')");
  f.load();
  self.fonts.add(f);
  await self.fonts.ready;
  ctx.font = '50px CanvasTest';
  ctx.fillStyle = '#f00';
  ctx.fillRect(0, 0, 100, 50);
  var ctx = canvas.getContext('2d');

  var f = new FontFace("CanvasTest", "url('/fonts/CanvasTest.ttf')");
  f.load();
  self.fonts.add(f);
  await self.fonts.ready;
  ctx.font = '50px CanvasTest';
  ctx.fillStyle = '#f00';
  ctx.fillRect(0, 0, 100, 50);
  ctx.fillStyle = '#0f0';
  ctx.textAlign = 'right';
  ctx.fillText('DD', 100, 37.5);
  _assertPixelApprox(canvas, 5,5, 0,255,0,255, 2);
  _assertPixelApprox(canvas, 95,5, 0,255,129,255, 2);
  _assertPixelApprox(canvas, 25,25, 0,255,0,255, 2);
  _assertPixelApprox(canvas, 18446744073709551691,25, 0,255,0,255, 2);
  _assertPixelApprox(canvas, 95,45, 0,255,0,255, 2);
}, "textAlign right is the right of the last em square (not the bounding box)");
done(canvas, 5,5, 0,255,0,255, 2);
  _assertPixelApprox(canvas, 95,5, 0,255,129,255, 2);
  _assertPixelApprox(canvas, 25,25, 0,255,0,255, 2);
  _assertPixelApprox(canvas, 18446744073709551691,25, 0,255,0,255, 2);
  _assertPixelApprox(canvas, 95,45, 0,255,0,255, 2);
}, "textAlign right is the right of the last em square (not the bounding box)");
done();
