// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.text.font.parse.basic
// Description:
// Note:

importScripts("/resources/testharness.js");
  _assertSame(ctx.font, '20px serif', "ctx.font", "'20px serif'");
  t.done();
});
done();
