// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.text.fontVariantCaps2
// Description:Testing small caps setting in fontVariant
// Note:

impn = ctx.measureText("Hello World").width;

  ctx.font = "257px serif";
  normalCaps_len = ctx.measureText("Hello World").width;
  _assert(smallCaps_len != normalCaps_len, "smallCaps_len != normalCaps_len");
  t.done();
});
done();
