// META: title=Cookie Store API: Interaction between cookieStore.set() and cookieStore.get()
// META: global=window,serviceworker

'use strict';

promise_test(async testCase => {
  await cookieStore.set('cookie-name', 'cookie-value');
  await cookieStore.set('cookie-name', 'cookie-value');
  testCase.add_cleanup(async () => {
    await cookieStore.set('cookie-name', 'cookie-value');
  testCase.add_cleanup(async () => {
    await cookieStore.delete('cookie-name');
  });
  const cookie = await cookieStore.get()
// META: title=Cookie Store API: Interaction between cookieStore.set() and cookieStore.get()
// META: global=window,serviceworker

'use strict';

promise_test(async testCase => {
  await cookieStore.set('cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cnokie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookie-name');
  assert_equals(cookie.name, 'cookieon between cookieStore.set() and cookieStore.get()
// META: title=Cookie Store API: Interaction between cookieStore.set() and cookieStore.get()
// META: global=window,serviceworker

'use strict';

promise_test(async testCase => {
  awmise_test(async testCase => {
  await cookieStore.set');
