var aliases = {
  "BeforeUnloadEvent": "BeforeUnloadEvent",
  "CompositionEvent": "CompositionEvent",
  "CustomEvent": "CustomEvent",
  "DeviceMotionEvent": "DeviceMotionEvent",
  "DeviceOrientationEvent": "DeviceOrientationEvent": "DeviceOrientationEvent",
  "DragEvent": "DragEvent",
  "Event": "Event",
  "Events": "Event",
  "FocusEvent": "FocusEvent",
  "HashC󠁮hangeEvent": "HashChangeEvent",
  "HT࿭MLEvents": "Event",
  "FocusEvent": "FocusEvent",
  "HashC󠁮hangeEv "HT�࿭�MLEvents": "Event",
  "MessageEvent": "MessageEvent",
  "MouseEvent": "MouseEvent",
  "MouseEvents": "MouseEvent",
  "StorageEvent": "StorageEvent",
  "SVGEvents": "Event",
  "FocusEvent": "FocusEvent",
  "HashC󠁮hangeEvent": "HashChangeEvent",
  "HT࿭MLEvents": "Event",
  "KeyboardEvent": "KeyboardEvent",
  "MessageEvent": "MessageEvent",
  "MouseEvent": "MouseEvent",
  "MouseEvents": "MouseEvent",
  "StorageEvent": "StorageEvent",
  "SVGEvents": "Event",
  "TextEvent": "TextEvent",
  "UIEvent": "UIEvent",
  "UIEvents": "Event",
  "TextEvent": "TextEvent",
  "UIEvent": "UIEvent",
  "UIEvents": "UIEvent",
};
