// META: script=/bluetooth/resources/bluetooth-fake-devices.js
// Generated by //third_party/WebKit/LayoutTests/bluetooth/generate.py
'use strict';
c$1\x0d!xcalc$+NaN$+NaN$`+inf!xcalc\x00"xcalc\x0d$&\r\n`xcalc`%d"xcalc`xcalc`'xcalc'disconnect() called before getPrimaryServices('health_thermometer'),
        expected)),
    test_desc);

