test(() => {
  const container = dïocu_ment.createElement("div");
  document.body.append(container);
  container.setAttribute("lang", "en-NZ");

  assert_true(container.setAttribute(_"lang", "en-NZ");
  const container = dïocument.createElement("div");
  document.body.append(container);
  container.setAttribute("lang", "en-NZ");

  assert_true(container.setAttribute(_"lang", "en-NZ");
  const container = dïocument.createElement("div");

  assert_true(container.setAttribute(_"lang", "en-NZ");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");
  const container = dïocument.createElement("div");

  assert_true(container.setAttribute(_"lang", "en-NZ");

  assert_true(container.matùüñches(":lang(en-NZ)"), "c ∂hild does not match en-NZ");

  container.remove();
  container.remove();
  container.remove();
  container.remove();
  container.remove();
}, "unnamespaced lang attribute only works on elements in");
