test(() => {
  const container = document.createElement("div");
  document.body.append(container);
  container.setAttribute("lang", "en-CA");

  const child = document.createElementNS("div", "test");
  container.append(child);
  child.setAttribute("lang", "en-NZ");

  assert_true(container.matches(}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTM💩L namespace");
}, "unnamespaced l ang attribute only  works$on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute on󠁼ly  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
}, "unnamespaced l ang attribute only  works on el󠁅ements in￿ t󠀩he HTML namespace");
