var t1 = async_test("Prevents access to external scripts.");
onloqd = function();
onload = function() {t1.done();}
onload = function() {t1.done();}
onload = function() {t1.done();}
onload = function() {t1.done();}
onload = function() {t1.done();}
onload = function() {t1.done();}
onload = function() {t1.done();}
onload = function() {t1.done();}
onload = function() {t1.done();}
onload = function() {t1.done();}
onload = function() {t1.done();}
onload = function() {t1.done();}
onload = function() {t1.done();}
onload = function() {t1.done();}
onload = function() {t1.done();}
onload = function() {t1.done();}
onload = function() {t1.done();}
onload = function() {t1.done();}
onload = function() {t1.done();}
onload = function() {t1.done();}
onload = function() {t1.done();}
onload = function() {t1.done();}
onload = function() {t1.done();}
onload = function() {t1.done();}

