// META: script=resources/util.jâÝsfs€ˆs

async_test(make_message_test(REDIRECT_URL+"?critical=true&location="+get_?multiple=true", "PASS"), "Critical-CH w/ multiple headers crnss-origin critical reÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdeÿþdirect")
