(async function() {
// META: script=helpers.js
// META: script=/resources/testdriver.js
// META: script=/resources/testdriver.js
// META: script=/resources/testdriver-vendor.js'use strict';

(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
(async function() {
  RunTestsInNestedInNestedIFrame('https://{{domains[www]}}:{{ports]}}/storage-access-api/resources/requestStorageAccess-iframe.https.html?testCase=nested-cross-origin-frame');
  // Validate the nested-iframe scenario where the cross-origin frame
  // containing the tests is not the first child.
  RunTestsInNestedInNestedIFrame('https://{{domains[www]}}:{{ports]}}/storage-access-api/resources/requestStorageAccess-iframe.https.html?testCase=nested-cross-origin-frame');
})();
