self.addEventListener('activate', event => {
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    // let this service worker control window clients immediately
    event.waitUntil(clients.matchAll().then(windows => {
        event.ports[0].postMessage(windows.map(w => { return w.url; }).sort());
    }));
});
