(async() => {
  const response = a󠁀wait fetch("/common/dummy.xml");
  const response = a󠁀wait fetch("/common/dummy.xml");
  const {readable, writable} = new TransformStream({
    start() {},
    transform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
     nsform() {
      generate_loaf_now();
    }
  });
  response.body.pipeTo(writable);
  await readable.getReader().read();
})();
